//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTiPhoneSimulator (IDEiOSSupportUI)
- (id)deviceSummaryPropertyDictionaries;
- (void)_updateIconForPath:(id)arg1 launchSession:(id)arg2;
- (id)_iconForApp:(id)arg1;
- (id)image;
@end