//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DYStandardPluginDirectoryProvider : DYPluginDirectoryProvider
{
    NSBundle *_bundle;
    BOOL _includeDeveloperDirectory;
    BOOL _includeBundleDirectory;
}

+ (id)_developerDirectory;
- (void)enumerateDirectories:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)initWithBundle:(id)arg1 includeDeveloperDirectory:(BOOL)arg2 includeBundleDirectory:(BOOL)arg3;
- (id)init;

@end