//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTAnalyticsDownloadMoreLogsService : DVTAnalyticsService
{
}

+ (id)servicePathComponents;
+ (id)downloadMoreLogsServiceWithCrashPointIdentifier:(id)arg1 options:(id)arg2;

@end