//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTAnalyticsCrashPointDeviceFamilyDistribution : NSObject <DVTServicesJSONSerialization>
{
    NSArray *_deviceFamilyData;
}

@property(readonly) NSArray *deviceFamilyData; // @synthesize deviceFamilyData=_deviceFamilyData;
- (void).cxx_destruct;
- (id)JSONRepresentation;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end