//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTAnalyticsResponse : NSObject
{
    NSDictionary *_payload;
}

+ (id)responseFromData:(id)arg1 httpResponse:(id)arg2 error:(id *)arg3;
@property(readonly) NSDictionary *payload; // @synthesize payload=_payload;
- (void).cxx_destruct;
- (id)initWithPayload:(id)arg1;

@end