//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTAnalyticsDownloadMoreLogsOptions : NSObject
{
    NSArray *_options;
}

+ (id)downloadMoreLogsOptionsWithLastCrashReportKey:(id)arg1 lastCrashPointTime:(id)arg2;
@property(readonly) NSArray *options; // @synthesize options=_options;
- (void).cxx_destruct;

@end