//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTAnalyticsCrashPointSummary : NSObject <DVTServicesJSONSerialization>
{
    NSString *_crashPointId;
    NSString *_crashPointString;
    NSString *_sourceFileName;
    NSNumber *_sourceFileLineNumber;
    NSNumber *_rollingOccurenceCount;
    NSNumber *_rollingUniqueDeviceCount;
}

@property(readonly) NSNumber *rollingUniqueDeviceCount; // @synthesize rollingUniqueDeviceCount=_rollingUniqueDeviceCount;
@property(readonly) NSNumber *rollingOccurenceCount; // @synthesize rollingOccurenceCount=_rollingOccurenceCount;
@property(readonly) NSNumber *sourceFileLineNumber; // @synthesize sourceFileLineNumber=_sourceFileLineNumber;
@property(readonly) NSString *sourceFileName; // @synthesize sourceFileName=_sourceFileName;
@property(readonly) NSString *crashPointString; // @synthesize crashPointString=_crashPointString;
@property(readonly) NSString *crashPointId; // @synthesize crashPointId=_crashPointId;
- (void).cxx_destruct;
- (id)JSONRepresentation;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end