//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTAnalyticsCrashPointDownloadData : DVTAnalyticsCrashPointData
{
    DVTAnalyticsCrashPointOSVersionDistribution *_osVersionDistribution;
    DVTAnalyticsCrashPointDeviceFamilyDistribution *_deviceFamilyDistribution;
    DVTAnalyticsCrashPointTimeDistribution *_crashPointTimeSeries;
    DVTAnalyticsCrashPointLogList *_logList;
}

+ (id)crashPointForSession:(id)arg1 crashPointIdentifier:(id)arg2 distributionOptions:(id)arg3 error:(id *)arg4;
@property(retain) DVTAnalyticsCrashPointLogList *logList; // @synthesize logList=_logList;
@property(retain) DVTAnalyticsCrashPointTimeDistribution *crashPointTimeSeries; // @synthesize crashPointTimeSeries=_crashPointTimeSeries;
@property(retain) DVTAnalyticsCrashPointDeviceFamilyDistribution *deviceFamilyDistribution; // @synthesize deviceFamilyDistribution=_deviceFamilyDistribution;
@property(retain) DVTAnalyticsCrashPointOSVersionDistribution *osVersionDistribution; // @synthesize osVersionDistribution=_osVersionDistribution;
- (void).cxx_destruct;
- (id)JSONRepresentation;

@end