//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTAnalyticsCrashPointDateDistributionOption : DVTAnalyticsServiceOption
{
}

+ (id)distributionWithStandardEndDate;
+ (id)distributionWithStandardStartDate;
+ (id)distributionWithDate:(id)arg1 type:(long long)arg2;
+ (id)_dateFormatter;
+ (id)_nameForType:(long long)arg1;
+ (void)initialize;

@end