//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTAnalyticsCrashPointDistributionOptions : NSObject
{
    NSArray *_options;
}

+ (id)distributionWithDefaultDateRangeAndDeviceFamilies:(id)arg1;
+ (id)distributionWithDefaultDateRangeAndOSVersions:(id)arg1;
+ (id)distributionWithDefaultDateRange;
+ (id)distributionStartDate:(id)arg1 endDate:(id)arg2 osVersions:(id)arg3 deviceFamilies:(id)arg4;
+ (id)_distributionWithStartDateDistro:(id)arg1 endDateDistro:(id)arg2 osVersions:(id)arg3 deviceFamilies:(id)arg4;
@property(readonly) NSArray *options; // @synthesize options=_options;
- (void).cxx_destruct;

@end