//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTAnalyticsServiceOption : NSObject
{
    NSString *_name;
    NSString *_value;
}

+ (id)dictionaryFromOptions:(id)arg1;
+ (id)optionWithName:(id)arg1 value:(id)arg2;
@property(readonly) NSString *value; // @synthesize value=_value;
@property(readonly) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)description;

@end