//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface GPUMTLTraceTextureDisplayableItem : GPUMTLTraceDisplayableItem
{
    id <GPUMTLDisplayableStrategy> _displayableStrategy;
}

+ (Class)blitDisplayableStrategyClass;
+ (Class)computeDisplayableStrategyClass;
- (void).cxx_destruct;
- (id)createRenderJobsForDisplaySet:(BOOL)arg1;
- (id)imageToExportToFile;
- (void)_connectElementResourceToDisplaySet:(unsigned long long)arg1 resourceObject:(id)arg2;
- (id)_startLoadingDisplaySetElement:(unsigned long long)arg1;
- (void)_displaySetLoadIsComplete:(id)arg1;
- (id)_startLoadingDisplaySet;
- (id)initWithController:(id)arg1 parent:(id)arg2 deviceID:(unsigned long long)arg3 functionIndex:(int)arg4 displayIndex:(int)arg5 displayableStrategyClass:(Class)arg6;

@end