//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface GPUMTLTraceOutline : GPUTraceOutline
{
    GPUMTLStateMirror *_stateMirror;
    unsigned long long _currentCommandBuffer;
    unsigned long long _currentCommandEncoder;
    struct stack<unsigned int, std::__1::deque<unsigned int, std::__1::allocator<unsigned int>>> _markerDepthStack;
    unsigned long long _currentParallelRenderCommandEncoder;
    unsigned long long _lastRenderCommandEncoder;
    NSMutableDictionary *_hidableItems;
    struct vector<unsigned int, std::__1::allocator<unsigned int>> _functionIndexToDisplayIndexMap;
    GPUMTLOutlineLabelCache *_labelCache;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)resourceDictionaryForResourceGroupID:(id)arg1;
- (id)labelForObjectID:(unsigned long long)arg1;
- (id)labelForArgument:(const struct Argument *)arg1 functionIndex:(unsigned int)arg2;
- (id)labelForReceiver:(const struct Function *)arg1 functionIndex:(unsigned int)arg2 hideCommandBuffersAndEncoders:(BOOL)arg3;
- (void)_processLabelForFunction:(const struct Function *)arg1 functionIndex:(unsigned int)arg2;
- (void)visitFunctionStreamFile:(id)arg1;
- (void)_addFunctionForDisplayableItem:(id)arg1;
- (void)_popDisclosureLevel;
- (void)_pushDisclosureLevelForObjectID:(unsigned long long)arg1 ofType:(unsigned int)arg2;
- (void)_pushDisclosureLevelWithLabel:(id)arg1;
- (void)_addAPIItemForFunction:(struct Function *)arg1 handleDisclosureLevel:(BOOL)arg2;
- (id)_addAPIItemForFunction:(struct Function *)arg1 markingAsHidden:(BOOL)arg2 handleDisclosureLevel:(BOOL)arg3;
- (void)_handleDisclosureLevelForFunction:(struct Function *)arg1;
- (void)_handleDisclosureLevelForFunction:(struct Function *)arg1 withCommandEncoderReceiver:(unsigned long long)arg2 andCommandEncoderType:(unsigned int)arg3;
- (unsigned int)_getObjectTypeForCommandEncoderCreation:(unsigned int)arg1;
- (void)_popCommandBuffer;
- (void)_popCommandEncoder;
- (id)stateMirrorForTraceItem:(id)arg1;
- (id)_derivedStateMirrorFromStateMirror:(id)arg1 forFunctionIndex:(unsigned int)arg2 fromFunctionIndex:(unsigned int)arg3;
- (id)initWithTraceSession:(id)arg1;

@end