//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface GPUMTLComputeEncoderStats : GPUMTLEncoderStats
{
    unsigned int _dispatchCalls;
}

@property(nonatomic) unsigned int dispatchCalls; // @synthesize dispatchCalls=_dispatchCalls;

@end