//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface GPUMTLRenderEncoderStats : GPUMTLEncoderStats
{
    unsigned int _drawCalls;
    unsigned long long _loadBandwidth;
    unsigned long long _storeBandwidth;
}

@property(nonatomic) unsigned long long storeBandwidth; // @synthesize storeBandwidth=_storeBandwidth;
@property(nonatomic) unsigned long long loadBandwidth; // @synthesize loadBandwidth=_loadBandwidth;
@property(nonatomic) unsigned int drawCalls; // @synthesize drawCalls=_drawCalls;
@property(readonly, nonatomic) unsigned long long loadStoreBandwidth;

@end