//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface GPUMTLFrameStats : NSObject
{
    unsigned int _drawCalls;
    unsigned int _dispatchCalls;
    unsigned int _renderEncoders;
    unsigned int _computeEncoders;
    unsigned int _blitEncoders;
    unsigned long long _loadBandwidth;
    unsigned long long _storeBandwidth;
}

@property(nonatomic) unsigned long long storeBandwidth; // @synthesize storeBandwidth=_storeBandwidth;
@property(nonatomic) unsigned long long loadBandwidth; // @synthesize loadBandwidth=_loadBandwidth;
@property(nonatomic) unsigned int blitEncoders; // @synthesize blitEncoders=_blitEncoders;
@property(nonatomic) unsigned int computeEncoders; // @synthesize computeEncoders=_computeEncoders;
@property(nonatomic) unsigned int renderEncoders; // @synthesize renderEncoders=_renderEncoders;
@property(nonatomic) unsigned int dispatchCalls; // @synthesize dispatchCalls=_dispatchCalls;
@property(nonatomic) unsigned int drawCalls; // @synthesize drawCalls=_drawCalls;
@property(readonly, nonatomic) unsigned long long loadStoreBandwidth;
@property(readonly, nonatomic) unsigned int displayableCalls;

@end