//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface GPUMTLOutlineLabelCache : NSObject
{
    NSMutableDictionary *_objectMap;
}

- (void).cxx_destruct;
- (void)setLabel:(id)arg1 forObjectID:(unsigned long long)arg2 functionIndex:(unsigned int)arg3;
- (id)labelForObjectID:(unsigned long long)arg1 functionIndex:(unsigned int)arg2;
- (id)labelForObjectID:(unsigned long long)arg1;
- (id)init;

@end