//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface GPUTraceResourceCollectionViewItem : UXCollectionViewCell
{
    GPUTraceResourceItem *_resourceItem;
    CALayer *_imageLayer;
    NSTextField *_label;
}

@property(retain, nonatomic) NSTextField *label; // @synthesize label=_label;
@property(retain, nonatomic) CALayer *imageLayer; // @synthesize imageLayer=_imageLayer;
@property(retain, nonatomic) GPUTraceResourceItem *resourceItem; // @synthesize resourceItem=_resourceItem;
- (void).cxx_destruct;
- (void)recalculateThumbnailWithScale:(double)arg1;
- (void)updateViewUsingRepresentedObject;
- (void)setSelected:(BOOL)arg1;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

@end