//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface GPUTraceResourcesEditor : GPUMainEditor <UXCollectionViewDelegate, UXCollectionViewDataSource, IDEGPUAssistantEditorAdditions, DVTFindBarFindable>
{
    GPUTraceModelFactory *_modelFactory;
    GPUTraceDocumentLocation *_currentLocation;
    NSDictionary *_previousEditorState;
    BOOL _loadingEditor;
    DVTObservingToken *_programShaderObserver;
    int _lastShaderType;
    GPUSharedTabUIState *_sharedTabState;
    NSString *_identifier;
    NSMutableArray *_resources;
    UXCollectionView *_resourceCollectionView;
    GPUResourceEditor *_currentSubViewController;
    NSScrollView *_resourceCollectionViewEnclosure;
}

+ (long long)version;
+ (void)configureStateSavingObjectPersistenceByName:(id)arg1;
+ (id)assetBundle;
+ (id)defaultViewNibBundle;
+ (id)defaultViewNibName;
@property(retain, nonatomic) NSScrollView *resourceCollectionViewEnclosure; // @synthesize resourceCollectionViewEnclosure=_resourceCollectionViewEnclosure;
@property(nonatomic) __weak GPUResourceEditor *currentSubViewController; // @synthesize currentSubViewController=_currentSubViewController;
@property(nonatomic) __weak UXCollectionView *resourceCollectionView; // @synthesize resourceCollectionView=_resourceCollectionView;
@property(retain, nonatomic) NSMutableArray *resources; // @synthesize resources=_resources;
- (void).cxx_destruct;
- (void)dumpImages:(id)arg1 asRaw:(BOOL)arg2;
- (void)collectionView:(id)arg1 itemWasDoubleClickedAtIndexPath:(id)arg2 withEvent:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (struct _NSRange)selectedRangeForFindBar:(id)arg1;
- (id)startingLocationForFindBar:(id)arg1 findingBackwards:(BOOL)arg2;
- (void)dvtFindBar:(id)arg1 didUpdateCurrentResult:(id)arg2;
- (void)dvtFindBar:(id)arg1 didUpdateResults:(id)arg2;
- (BOOL)findBarSupported;
- (void)_takeStateDictionaryFromPreviousGPUAssistantEditor:(id)arg1;
- (BOOL)_shouldInstallGPUEditorWithPreviousStateDictionaryOrNil:(id)arg1;
- (void)commitStateToDictionary:(id)arg1;
- (void)revertStateWithDictionary:(id)arg1;
- (id)_findOutlineItemForHistoryAction;
- (id)_currentAssistantDocumentLocations;
- (id)_getSubEditorItemFromPreviousEditorState;
- (void)showResourceItem:(id)arg1;
- (void)_openResourceLocation:(id)arg1;
- (void)handleOpenScrubberTriggeredNewLocation:(id)arg1;
- (void)handleDebugBarNavigationWithDocumentLocation:(id)arg1;
- (void)selectDocumentLocations:(id)arg1;
- (id)currentSelectedDocumentLocations;
- (id)currentSelectedItems;
- (void)_setCurrentLocation:(id)arg1;
- (void)_loadResourceEditorForNavItem:(id)arg1;
- (void)_handleFunctionResourceItem:(id)arg1;
- (id)_findNavigableForShaderItem:(id)arg1;
- (BOOL)_isValidSourceURLPathForShaderItem:(id)arg1;
- (id)_editorForResourceItem:(id)arg1;
- (void)handleResourceItemThumbnailsRecalculation:(id)arg1;
- (void)handleReloadResourceItem:(id)arg1;
- (void)resetResourcesInTree:(id)arg1;
- (void)_resetResource:(id)arg1;
- (void)_loadRelevantDisplayableForProgramOrShaderItem:(id)arg1;
- (void)didSetupEditor;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (void)primitiveInvalidate;
- (void)loadView;
- (void)_initCollectionView;
- (void)takeFocus;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end