//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface _DTTimelineTileDecorationOperation : NSObject
{
    struct unique_ptr<DTTimelineDecorationContainer, std::__1::default_delete<DTTimelineDecorationContainer>> _containerPtr;
    DTTimelineTile *_tile;
    DTTimelineDecorator *_decorator;
    NSOperation *_fillOp;
    NSOperation *_stringSummaryOp;
    NSDate *_graceWindow;
    NSTimer *_timer;
    BOOL _stale;
    BOOL _missedInitialDrawOpportunity;
    DTTimelineInspectionDecorationContainer *_summaryContainer;
}

@property(nonatomic) BOOL missedInitialDrawOpportunity; // @synthesize missedInitialDrawOpportunity=_missedInitialDrawOpportunity;
@property(nonatomic, getter=isStale) BOOL stale; // @synthesize stale=_stale;
@property(readonly, nonatomic) DTTimelineInspectionDecorationContainer *summaryContainer; // @synthesize summaryContainer=_summaryContainer;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)go;
- (void)abandon;
- (void)_drawingFinished;
@property(readonly, nonatomic) BOOL shouldShowPlaceholder;
@property(readonly, nonatomic, getter=isStringSummarizationFinished) BOOL stringSummarizationFinished;
@property(readonly, nonatomic, getter=isDrawingFinished) BOOL drawingFinished;
@property(readonly, nonatomic) struct DTTimelineDecorationContainer *container;
- (id)initWithTile:(id)arg1 container:(struct DTTimelineDecorationContainer *)arg2 decorator:(id)arg3 eta:(id)arg4;
- (void)_timerFired:(id)arg1;

@end