//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DTFilenameFormatter : NSFormatter
{
    BOOL _showPathExtensions;
}

- (id)stringForObjectValue:(id)arg1;
- (BOOL)showPathExtensions;
- (void)setShowPathExtensions:(BOOL)arg1;
- (id)init;

@end