//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DTNetworkGraph : DTBarGraph
{
    struct CGRect _contentBox;
    id <DTNetworkGraphLayout> layout;
    NSArray *_nodes;
    NSArray *_edges;
    DTNetworkGraphObject *_selectedObject;
}

@property(retain) DTNetworkGraphObject *selectedObject; // @synthesize selectedObject=_selectedObject;
@property(retain) NSArray *edges; // @synthesize edges=_edges;
@property(retain) NSArray *nodes; // @synthesize nodes=_nodes;
- (void).cxx_destruct;
- (void)mouseDown:(id)arg1;
@property(retain, getter=_layoutDelegate, setter=_setLayoutDelegate:) id <DTNetworkGraphLayout> layout;
- (void)observeModel:(BOOL)arg1;
- (void)setFrameSize:(struct CGSize)arg1;
- (void)resetPaths;
- (void)createNodesAndEdges;
- (void)drawXAxis:(struct CGRect)arg1;
- (void)drawYAxis:(struct CGRect)arg1;
- (void)drawContent:(struct CGRect)arg1;
- (void)drawBorder:(struct CGRect)arg1;
- (double)calculateVerticalBorderBuffer;
- (double)calculateHorizontalBorderBuffer;
- (id)init;

@end