//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DTTimelineGraphLayoutManager : NSObject
{
    DTTimelineGraph *_timelineGraph;
    DTTimelineGraphLayoutManagerLayerDelegate *_layerDelegate;
    CALayer *_inspectionPointLayer;
    CALayer *_leftSelectionIndicatorLayer;
    CALayer *_rightSelectionIndicatorLayer;
    CALayer *_leftSelectionPointLayer;
    CALayer *_rightSelectionPointLayer;
    CALayer *_inspectionSummaryLayer;
    CIFilter *_colorEffect;
    BOOL _displayInspectionSummary;
    unsigned long long _inspectionInfoSummaryTime;
    NSSet *_inspectionSummaryContainers;
    double _computedHeight;
    NSSet *_visiblePlanes;
    struct shared_ptr<std::__1::unordered_map<int, CGRect, std::__1::hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<const int, CGRect>>>> _planeLayoutMapRef;
    BOOL _animateChanges;
}

@property(nonatomic) BOOL animateChanges; // @synthesize animateChanges=_animateChanges;
- (id).cxx_construct;
- (void).cxx_destruct;
- (const unordered_map_c1fbcd3c *)planeLayoutMap;
- (double)computedHeight;
- (void)addBottomBorderLayer:(id)arg1;
- (void)clearInspectionSummary;
- (void)displayInspectionSummaryForNanosecond:(unsigned long long)arg1;
- (void)addDecorationSummaryLayer:(id)arg1;
- (id)planeAtPoint:(struct CGPoint)arg1;
- (void)layoutSublayersOfLayer:(id)arg1;
- (void)_positionFullHeightPlane:(id)arg1;
- (void)_positionPlane:(id)arg1 includeBottomBorder:(BOOL)arg2;
- (void)_positionBottomBorderForPlane:(id)arg1;
- (void)generatePlaneLayoutMap;
- (void)_addPlaneToMap:(id)arg1 distanceFromTop:(double)arg2;
- (void)_udpateVisiblePlanes:(id)arg1;
- (void)_layoutInspectionSummary:(id)arg1;
- (void)_layoutSelection:(id)arg1;
- (void)_layoutInspectionPoint:(id)arg1;
- (id)initWithTimelineGraph:(id)arg1;

@end