//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DTTimelineRulerBackgroundDecorator : DTTimelineDecorator
{
    NSDictionary *_attributes;
}

- (void).cxx_destruct;
- (void)setDefaultsForPlane:(id)arg1;
- (id)decorateContainer:(struct DTTimelineDecorationContainer *)arg1;
- (id)init;
- (id)initWithTimeLabelAttributes:(id)arg1;

@end