//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DTTimelineGraphInfoSummaryLabelLayer : CALayer
{
    NSAttributedString *_string;
}

@property(copy, nonatomic) NSAttributedString *string; // @synthesize string=_string;
- (void).cxx_destruct;
- (void)drawInContext:(struct CGContext *)arg1;
- (struct CGSize)preferredFrameSize;

@end