//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DTTimelineGraphPlaneManager : NSObject
{
    DTTimelineGraph *_timelineGraph;
    NSMutableArray *_planes;
    DTTimelinePlane *_topPinnedPlane;
    DTTimelinePlane *_bottomPinnedPlane;
    DTTimelinePlane *_backgroundPlane;
    DTTimelinePlane *_overlayPlane;
    BOOL _topPlaneChanged;
    BOOL _bottomPlaneChanged;
    BOOL _backgroundPlaneChanged;
    BOOL _overlayPlaneChanged;
    BOOL _planesChanged;
    NSMapTable *_planeGroupChangesMap;
}

+ (id)planeManagerWithTimelineGraph:(id)arg1;
- (void).cxx_destruct;
- (void)removeAllSubplanesFromPlaneGroup:(id)arg1;
- (void)removeSubplane:(id)arg1 fromPlaneGroup:(id)arg2;
- (void)insertSubplane:(id)arg1 afterSubplane:(id)arg2 inPlaneGroup:(id)arg3;
- (void)addSubplanes:(id)arg1 toPlaneGroup:(id)arg2;
- (void)addSubplane:(id)arg1 toPlaneGroup:(id)arg2;
- (void)removeAllPlanes;
- (void)removePlane:(id)arg1;
- (void)insertPlane:(id)arg1 afterPlane:(id)arg2;
- (void)addPlanes:(id)arg1;
- (void)addPlane:(id)arg1;
- (void)removeOverlayPlane;
- (void)removeBackgroundPlane;
- (void)removeBottomPinnedPlane;
- (void)removeTopPinnedPlane;
- (void)setOverlayPlane:(id)arg1;
- (void)setBackgroundPlane:(id)arg1;
- (void)setBottomPinnedPlane:(id)arg1;
- (void)setTopPinnedPlane:(id)arg1;
- (void)commitChangesAnimated:(BOOL)arg1;
- (void)_reset;
- (id)initWithTimelineGraph:(id)arg1;

@end