//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DTTimelineDecoratedPlane : DTTimelinePlane
{
    NSMapTable *_tilesByIdx;
    double _oldTileWidth;
    struct CGSize _defaultDrawableIconSize;
    DTTimelineGraphInfoSummaryLabelLayer *_infoSummaryLabelLayer;
    BOOL _dynamicRangeValid;
    BOOL _skipFaultingInTiles;
    DTTimelineDecorator *_decorator;
    NSColor *_defaultDrawableColor;
    NSImage *_defaultDrawableIcon;
    NSString *_dynamicRangePeerGroup;
    NSAttributedString *_summary;
    struct DTTimelineGraphDynamicRange _minimalDynamicRange;
    struct DTTimelineGraphDynamicRange _maximumDynamicRange;
}

+ (id)planeWithDecorator:(id)arg1;
@property(retain, nonatomic) NSAttributedString *summary; // @synthesize summary=_summary;
@property(copy, nonatomic) NSString *dynamicRangePeerGroup; // @synthesize dynamicRangePeerGroup=_dynamicRangePeerGroup;
@property(nonatomic) struct DTTimelineGraphDynamicRange maximumDynamicRange; // @synthesize maximumDynamicRange=_maximumDynamicRange;
@property(nonatomic) struct DTTimelineGraphDynamicRange minimalDynamicRange; // @synthesize minimalDynamicRange=_minimalDynamicRange;
@property(nonatomic) struct CGSize defaultDrawableIconSize; // @synthesize defaultDrawableIconSize=_defaultDrawableIconSize;
@property(nonatomic) NSImage *defaultDrawableIcon; // @synthesize defaultDrawableIcon=_defaultDrawableIcon;
@property(copy, nonatomic) NSColor *defaultDrawableColor; // @synthesize defaultDrawableColor=_defaultDrawableColor;
@property(readonly, nonatomic) DTTimelineDecorator *decorator; // @synthesize decorator=_decorator;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)_didMoveOutOfView;
- (void)_willMoveIntoView;
- (id)_decorationSummaryLayer;
- (void)makeOpaqueWithBackgroundColor:(id)arg1;
- (id)visibleStringSummaries;
- (void)setHeight:(double)arg1;
- (double)height;
@property(nonatomic) BOOL decoratesMajorMinorTicks;
@property(nonatomic) unsigned long long intervalBarWidth;
@property(nonatomic) double intervalVisualSpacing;
@property(nonatomic) unsigned long long intervalDisplayType;
@property(nonatomic) unsigned long long intervalConflictResolutionType;
@property(nonatomic) unsigned long long pointDisplayType;
@property(nonatomic) unsigned long long pointConflictResolutionType;
- (BOOL)dynamicRangeWasSet;
- (void)setDynamicRange:(struct DynamicRange)arg1;
- (struct DynamicRange)currentDynamicRange;
- (struct DynamicRange)visibleDynamicRange;
- (void)_enumerateVisibleTiles:(CDUnknownBlockType)arg1;
- (id)_decoratedPlanes;
- (void)_contextChanged;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (id)init;
- (id)initWithDecorator:(id)arg1;
- (void)_invalidateTimeRange:(struct XRTimeRange)arg1;
- (void)_clearTileCache;
- (void)_setPosition:(struct CGPoint)arg1 size:(struct CGSize)arg2;
- (void)_layoutTiles;
- (void)_removeFromContext;
- (void)_setContext:(struct TimelineViewContext *)arg1 layer:(id)arg2 anchorPoint:(struct CGPoint)arg3;

@end