//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DTTimelinePlaneInspectionDecorationInfo : NSObject
{
    DTTimelinePlane *_plane;
    DTTimelineInspectionDecoration *_inspectionDecoration;
    double _yPosition;
}

@property(readonly, nonatomic) double yPosition; // @synthesize yPosition=_yPosition;
@property(readonly, nonatomic) DTTimelineInspectionDecoration *inspectionDecoration; // @synthesize inspectionDecoration=_inspectionDecoration;
@property(readonly, nonatomic) DTTimelinePlane *plane; // @synthesize plane=_plane;
- (void).cxx_destruct;
- (id)initWithPlane:(id)arg1 inspectionDecoration:(id)arg2 yPosition:(double)arg3;

@end