//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DTTimelinePlaneGroupChanges : NSObject
{
    DTTimelinePlaneGroup *_planeGroup;
    BOOL _hasChanges;
    NSMutableArray *_subplanes;
}

@property(nonatomic) BOOL hasChanges; // @synthesize hasChanges=_hasChanges;
@property(retain, nonatomic) NSMutableArray *subplanes; // @synthesize subplanes=_subplanes;
- (void).cxx_destruct;
- (id)initWithPlaneGroup:(id)arg1;

@end