//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTProxiediOSDevice : NSObject <DVTBasicDevice>
{
    DTDKRemoteDeviceToken *_token;
}

+ (id)keyPathsForValuesAffectingProcessorDescription;
+ (id)keyPathsForValuesAffectingOperatingSystemBuild;
+ (id)keyPathsForValuesAffectingOperatingSystemVersion;
+ (id)keyPathsForValuesAffectingModelCode;
+ (id)keyPathsForValuesAffectingModelUTI;
+ (id)keyPathsForValuesAffectingModelName;
+ (id)keyPathsForValuesAffectingNameForDeveloperPortal;
+ (id)keyPathsForValuesAffectingName;
+ (id)keyPathsForValuesAffectingIdentifier;
@property(readonly) DTDKRemoteDeviceToken *token; // @synthesize token=_token;
- (void).cxx_destruct;
@property(readonly) BOOL supportsProvisioning;
@property(readonly, copy) NSString *platformIdentifier;
@property(readonly, copy) NSString *processorDescription;
@property(readonly, copy) NSString *operatingSystemBuild;
@property(readonly, copy) NSString *operatingSystemVersion;
@property(readonly, copy, nonatomic) NSString *modelCode;
@property(readonly, copy, nonatomic) NSString *modelUTI;
@property(readonly, copy, nonatomic) NSString *modelName;
@property(readonly, copy) NSString *nameForDeveloperPortal;
@property(readonly, copy) NSString *name;
@property(readonly, copy) NSString *identifier;
- (BOOL)isEqual:(id)arg1;
@property(readonly) unsigned long long hash;
@property(readonly, copy) NSSet *proxiedDevices;
- (id)initWithToken:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end