//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDELaunchiPhoneSimulatorLauncher : IDERunOperationWorker <IDERunOperationWorkerChaining, DTMISProcessControlServiceAuthorizedAPI>
{
    BOOL _debugSessionStarted;
    BOOL _responsibleForTermination;
    BOOL _setUpSimulatorSessionForAttaching;
    BOOL _terminateCalled;
    BOOL _notifiedTracker;
    DVTDispatchLock *_lifeCycleLock;
    DVTObservingToken *_debugSessionStateObservingToken;
    BOOL _launchingToDebug;
    DVTiPhoneSimulator *_device;
    IDEPseudoTerminal *_pty;
    DTXChannel *_launchServiceChannel;
}

@property(retain) DTXChannel *launchServiceChannel; // @synthesize launchServiceChannel=_launchServiceChannel;
@property(retain) IDEPseudoTerminal *pty; // @synthesize pty=_pty;
@property(retain) DVTiPhoneSimulator *device; // @synthesize device=_device;
@property(getter=isLaunchingToDebug) BOOL launchingToDebug; // @synthesize launchingToDebug=_launchingToDebug;
- (void).cxx_destruct;
- (void)_showTodayView;
- (BOOL)_willUseExistingProcess:(id)arg1;
- (void)pidDiedCallback:(id)arg1;
- (void)_cancelProcessControlChannel;
- (id)_instrumentsProcessControlChannel;
- (void)launchCompleteWithAppPID:(int)arg1 simulatorPID:(int)arg2;
- (void)executionDidEnd;
- (void)terminate;
- (void)start;
- (void)_setUpSimulatorSessionForAttaching;
- (void)_finishCurrentWorkAndNotifyTracker:(id)arg1;
- (void)primitiveInvalidate;
- (id)initWithExtensionIdentifier:(id)arg1 launchSession:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end