//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol XCSUIIntegrationSteppedProgressViewLabelProvider <NSObject>
- (NSString *)informativeStringForSteppedProgressView:(XCSUIIntegrationSteppedProgressView *)arg1 integrationStep:(long long)arg2;
- (NSString *)labelForSteppedProgressView:(XCSUIIntegrationSteppedProgressView *)arg1 integrationStep:(long long)arg2;
@end