//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface Xcode3UnnecessaryBuildFiles : Xcode3UpgradeTargetTask
{
    NSSet *_unnecessaryBuildFiles;
}

+ (id)analyzeInContext:(id)arg1;
+ (id)_UTIsOfUnnecessaryBuildFiles;
- (void).cxx_destruct;
- (BOOL)upgrade;

@end