//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface Xcode3TargetPortalEntitlementsCoordinatorSnapshot : NSObject
{
    NSString *_bundleIdentifier;
    NSString *_codesignIdentity;
    NSString *_profileUUID;
    NSString *_platformIdentifier;
    NSString *_teamID;
    DVTDeveloperAccount *_developerAccount;
    id <DVTCodesignableDevice> _targetDevice;
    NSSet *_proxiedDevices;
}

@property(retain, nonatomic) NSSet *proxiedDevices; // @synthesize proxiedDevices=_proxiedDevices;
@property(retain, nonatomic) id <DVTCodesignableDevice> targetDevice; // @synthesize targetDevice=_targetDevice;
@property(retain, nonatomic) DVTDeveloperAccount *developerAccount; // @synthesize developerAccount=_developerAccount;
@property(copy, nonatomic) NSString *teamID; // @synthesize teamID=_teamID;
@property(retain, nonatomic) NSString *platformIdentifier; // @synthesize platformIdentifier=_platformIdentifier;
@property(copy, nonatomic) NSString *profileUUID; // @synthesize profileUUID=_profileUUID;
@property(copy, nonatomic) NSString *codesignIdentity; // @synthesize codesignIdentity=_codesignIdentity;
@property(copy, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
- (void).cxx_destruct;

@end