#import <ParseKit/PKSParser.h>

enum {
    OBJCFUNCORMETHODPARSER_TOKEN_KIND_SUPER = 14,
    OBJCFUNCORMETHODPARSER_TOKEN_KIND_OPENSQUAREPAREN,
    OBJCFUNCORMETHODPARSER_TOKEN_KIND_COMMA,
    OBJCFUNCORMETHODPARSER_TOKEN_KIND_OPENPAREN,
    OBJCFUNCORMETHODPARSER_TOKEN_KIND_COLON,
    OBJCFUNCORMETHODPARSER_TOKEN_KIND_CLOSESQUAREPAREN,
    OBJCFUNCORMETHODPARSER_TOKEN_KIND_CLOSEPAREN,
};

@interface ObjCFuncOrMethodParser : PKSParser

@end

