//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface PBXAEEditorSpecification : PBXExternalEditorSpecification
{
}

+ (void)_handleExternalEditorDidSaveEvent:(id)arg1 withReply:(id)arg2;
+ (void)registerForExternalEditorAppleEvents;
- (BOOL)_sendSaveDocumentEventForFile:(id)arg1;
- (id)_modifiedFileDictionary;
- (id)modifiedDocumentsArray;
- (BOOL)saveFile:(id)arg1;

@end