//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface PBXBuildSettingsAspectModule : PBXProjectModule
{
    PBXBuildSettingsDictionary *_buildSettings;
    PBXWidgetGroup *_widgetGroup;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
- (void)update;
- (id)widgetGroup;
- (id)buildSettings;
- (void)viewDidLoad;
- (void)dealloc;
- (void)updateWithBuildSettings:(id)arg1;
- (id)initWithBuildSettings:(id)arg1;

@end