//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface PBXLoadableWizardProxy : NSObject <PBXWizardProxies>
{
    NSString *_categorizedWizardName;
    NSString *_wizardBundlePath;
    NSBundle *_wizardBundle;
}

+ (id)proxyWithWizardBundlePath:(id)arg1 categorizedWizardName:(id)arg2;
- (id)icon;
- (id)instantiateWizardWithParent:(id)arg1;
- (id)categorizedWizardNames;
- (void)dealloc;
- (id)initWithWizardBundlePath:(id)arg1 categorizedWizardName:(id)arg2;

@end