//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDECrashLog : IDEDebugProcess
{
    IDECrashPoint *_crashPoint;
    IDEStackFrame *_crashingStackFrame;
}

@property(retain, nonatomic) IDEStackFrame *crashingStackFrame; // @synthesize crashingStackFrame=_crashingStackFrame;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (BOOL)isPaused;
- (id)parentDebugSession;
- (id)associatedProcessUUID;
- (id)initWithCrashPoint:(id)arg1;
- (id)init;
- (id)initWithDebugSession:(id)arg1;

@end