//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEOCUnitTestRunnerOperation : IDERunOperation
{
    BOOL _shouldDeleteScopeFile;
    DVTFilePath *_testScopeFilePath;
}

@property BOOL shouldDeleteScopeFile; // @synthesize shouldDeleteScopeFile=_shouldDeleteScopeFile;
@property(retain) DVTFilePath *testScopeFilePath; // @synthesize testScopeFilePath=_testScopeFilePath;
- (void).cxx_destruct;
- (void)runningDidFinish;

@end