//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEProductType : NSObject
{
}

+ (id)productTypeForIdentifier:(id)arg1 platform:(id)arg2;
- (BOOL)shouldAutocreateSchemes;
- (BOOL)isWatchAppExtension;
- (BOOL)isWatchApplication;
- (BOOL)isAppExtension;
- (BOOL)isApplication;
- (BOOL)isKindOfProductType:(id)arg1;
@property(readonly) IDEProductType *superType;
@property(readonly) DVTPlatform *platform;
@property(readonly) NSString *localizedDescription;
@property(readonly) NSString *name;
@property(readonly) NSString *identifier;

@end