//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEProfileOperation : DVTOperation
{
    IDELaunchParametersSnapshot *_launchParameters;
}

+ (id)operationWithLaunchParametersSnapshot:(id)arg1 block:(CDUnknownBlockType)arg2;
@property(retain) IDELaunchParametersSnapshot *launchParameters; // @synthesize launchParameters=_launchParameters;
- (void).cxx_destruct;

@end