//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEStructureEditingHelper : NSObject
{
}

+ (id)distinctFilePathForCopyOf:(id)arg1;
+ (id)distinctFilePathForNewFileIn:(id)arg1 withName:(id)arg2 andExtension:(id)arg3;
+ (id)distinctFilePathForNewUntitledFolderIn:(id)arg1;
+ (id)distinctFilePathInParent:(id)arg1 withProposedName:(id)arg2 andExtension:(id)arg3;

@end