//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEShellXPCDebugSession : IDEDebugSession
{
    id <IDEDebugTopNavigableModel> _topNavigableModel;
}

- (void)setTopNavigableModel:(id)arg1;
- (id)topNavigableModel;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (id)initWithName:(id)arg1;
- (id)init;

@end