//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IBResourceReaderCacheReferencer : NSObject
{
    NSDictionary *referencedCacheEntries;
}

@property(copy) NSDictionary *referencedCacheEntries; // @synthesize referencedCacheEntries;
- (void)dealloc;
- (id)init;

@end