//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface _DVTCrashPointAppStoreListResult : NSObject
{
    DVTAnalyticsAppIdentifier *_appIdentifier;
    NSError *_error;
    DVTAnalyticsCrashPointList *_list;
}

+ (id)resultWithAppIdentifier:(id)arg1 listOrNil:(id)arg2 errorOrNil:(id)arg3;
@property(readonly) DVTAnalyticsCrashPointList *list; // @synthesize list=_list;
@property(readonly) NSError *error; // @synthesize error=_error;
@property(readonly) DVTAnalyticsAppIdentifier *appIdentifier; // @synthesize appIdentifier=_appIdentifier;
- (void).cxx_destruct;

@end