//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTAnalyticsSnapshot : NSObject
{
    DVTFilePath *_filePath;
    NSData *_data;
    NSArray *_childSnapshots;
}

@property(readonly, nonatomic) NSArray *childSnapshots; // @synthesize childSnapshots=_childSnapshots;
@property(readonly, nonatomic) NSData *data; // @synthesize data=_data;
@property(readonly, nonatomic) DVTFilePath *filePath; // @synthesize filePath=_filePath;
- (void).cxx_destruct;
- (id)description;
- (BOOL)writeToCachePathWithError:(id *)arg1;
- (id)initWithFilePath:(id)arg1 data:(id)arg2 childSnapshots:(id)arg3;

@end