//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTCrashLogProvider : NSObject <DVTServicesFileSystemSerialization>
{
    NSOrderedSet *_crashLogIdentifiers;
    DVTFilePath *_cacheDirectory;
    NSMutableDictionary *_crashLogDict;
}

+ (id)objectFromFilePath:(id)arg1 error:(id *)arg2;
+ (id)crashLogProviderWithCacheDirectory:(id)arg1 crashLogIdentifiers:(id)arg2;
@property(retain, nonatomic) NSMutableDictionary *crashLogDict; // @synthesize crashLogDict=_crashLogDict;
@property(readonly, nonatomic) DVTFilePath *cacheDirectory; // @synthesize cacheDirectory=_cacheDirectory;
@property(retain) NSOrderedSet *crashLogIdentifiers; // @synthesize crashLogIdentifiers=_crashLogIdentifiers;
- (void).cxx_destruct;
- (BOOL)writeToFilePath:(id)arg1 error:(id *)arg2;
- (BOOL)_writeCrashLogSnapshots:(id)arg1 error:(id *)arg2;
- (id)crashLogRecordAtIndex:(unsigned long long)arg1;
- (id)crashLogRecordForCrashLogIdentifier:(id)arg1;
- (void)addCrashLogs:(id)arg1;
- (void)_flushInMemoryCache;
- (id)crashLogSavingQueue;
- (id)initWithCacheDirectory:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end