//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTCrashPointRecordObserved : NSObject
{
    DVTCrashPointRecord *_crashPointRecord;
    NSArray *_observationTokens;
}

@property(readonly) NSArray *observationTokens; // @synthesize observationTokens=_observationTokens;
@property(readonly) DVTCrashPointRecord *crashPointRecord; // @synthesize crashPointRecord=_crashPointRecord;
- (void).cxx_destruct;
- (id)initWithCrashPointRecord:(id)arg1 observationTokens:(id)arg2;

@end