//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTCrashPointRecord : NSObject <DVTAnalyticsSnapshotFileSystemSerialization>
{
    DVTAnalyticsCrashPointIdentifier *_crashPointIdentifier;
    DVTCrashPointUserData *_userData;
    NSString *_crashPointString;
    NSString *_sourceFileName;
    unsigned long long _sourceFileLine;
    DVTFilePath *_cachePath;
    NSMutableDictionary *_crashPointForFilter;
}

+ (id)objectFromFilePath:(id)arg1 error:(id *)arg2;
@property(retain) NSMutableDictionary *crashPointForFilter; // @synthesize crashPointForFilter=_crashPointForFilter;
@property(retain) DVTFilePath *cachePath; // @synthesize cachePath=_cachePath;
@property unsigned long long sourceFileLine; // @synthesize sourceFileLine=_sourceFileLine;
@property(retain) NSString *sourceFileName; // @synthesize sourceFileName=_sourceFileName;
@property(retain) NSString *crashPointString; // @synthesize crashPointString=_crashPointString;
@property(readonly) DVTCrashPointUserData *userData; // @synthesize userData=_userData;
@property(readonly) DVTAnalyticsCrashPointIdentifier *crashPointIdentifier; // @synthesize crashPointIdentifier=_crashPointIdentifier;
- (void).cxx_destruct;
- (id)snapshotWithError:(id *)arg1;
- (id)_crashPointSnapshotsWithError:(id *)arg1;
- (id)_infoJSON;
- (id)crashPointForFilter:(id)arg1;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithIdentifier:(id)arg1 userData:(id)arg2 crashPointString:(id)arg3 sourceFileName:(id)arg4 sourceFileLine:(unsigned long long)arg5 cachePath:(id)arg6;

@end