//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTCrashLogSection : NSObject
{
    NSData *_data;
    struct _NSRange _labelRange;
    struct _NSRange _contentRange;
}

+ (id)sectionsFromData:(id)arg1 error:(id *)arg2;
@property(readonly) NSData *data; // @synthesize data=_data;
- (id).cxx_construct;
- (void).cxx_destruct;
@property(readonly) NSArray *contentLines;
@property(readonly) NSString *contents;
@property(readonly) NSString *label;
- (id)initWithData:(id)arg1 labelStart:(const char *)arg2 labelEnd:(const char *)arg3 contentsStart:(const char *)arg4 contentsEnd:(const char *)arg5;

@end