//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTCrashLogRecord : NSObject
{
    NSString *_crashLogIdentifier;
    DVTCrashLog *_locatedCrashLog;
    NSError *_locationError;
}

@property(readonly) NSError *locationError; // @synthesize locationError=_locationError;
@property(readonly) DVTCrashLog *locatedCrashLog; // @synthesize locatedCrashLog=_locatedCrashLog;
@property(readonly) NSString *crashLogIdentifier; // @synthesize crashLogIdentifier=_crashLogIdentifier;
- (void).cxx_destruct;
- (id)description;
- (id)initWithCrashLogIdentifier:(id)arg1 locatedCrashLog:(id)arg2 locationError:(id)arg3;

@end