//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTCrashPointAppStoreSource : NSObject <DVTInvalidation>
{
    DVTAnalyticsAppIdentifier *_appIdentifier;
    NSMapTable *_filterToSourceMap;
    NSMapTable *_identifierToCrashPointRecordObservedMap;
    DVTCrashPointParameters *_parameters;
    DVTFilePath *_cachePath;
}

+ (id)_timestampLock;
+ (void)invalidateCachedTimestamps;
+ (void)initialize;
@property(readonly) DVTFilePath *cachePath; // @synthesize cachePath=_cachePath;
@property(readonly) DVTCrashPointParameters *parameters; // @synthesize parameters=_parameters;
@property(readonly) NSMapTable *identifierToCrashPointRecordObservedMap; // @synthesize identifierToCrashPointRecordObservedMap=_identifierToCrashPointRecordObservedMap;
@property(readonly) NSMapTable *filterToSourceMap; // @synthesize filterToSourceMap=_filterToSourceMap;
@property(readonly) DVTAnalyticsAppIdentifier *appIdentifier; // @synthesize appIdentifier=_appIdentifier;
- (void).cxx_destruct;
- (void)_populateParametersToSourceMap;
- (id)_crashPointRecordForIdentifier:(id)arg1;
- (void)_setUserDataObservationTokenForCrashPointRecord:(id)arg1;
- (id)pathOfCrashPointRecordForCrashPointIdentifier:(id)arg1;
- (id)cachedCrashPointsForFilter:(id)arg1 error:(id *)arg2;
- (void)cacheCrashPoints:(id)arg1;
- (id)_cacheLock;
- (id)cachedLastRefreshDateForFilter:(id)arg1;
- (void)cacheLastRefreshDate:(id)arg1 forFilter:(id)arg2;
- (id)crashPointRecordForIdentifier:(id)arg1 summary:(id)arg2;
- (id)parameterizedSourceForFilter:(id)arg1;
- (void)primitiveInvalidate;
- (id)initWithAppIdentifier:(id)arg1 parameters:(id)arg2 cachePath:(id)arg3;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end