//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTCrashPointParameterizedAppStoreSource : DVTCrashPointSource
{
    NSMutableArray *_crashPoints;
    BOOL _bypassTimestampRestrictions;
    BOOL _bypassCache;
    NSArray *_defaultCrashPointListOptions;
    DVTAnalyticsCrashPointDistributionOptions *_defaultCrashPointDownloadOptions;
    DVTAnalyticsDownloadMoreLogsOptions *_defaultCrashPointMoreLogsOptions;
    Class _crashPointListClass;
    Class _crashPointDownloadDataClass;
    Class _crashPointMoreLogsClass;
    DVTCrashPointAppStoreSource *_appStoreSource;
    DVTCrashPointParameters *_filteredParameters;
    DVTCrashPointFilter *_filter;
}

+ (void)initialize;
@property(readonly) DVTCrashPointFilter *filter; // @synthesize filter=_filter;
@property(readonly) DVTCrashPointParameters *filteredParameters; // @synthesize filteredParameters=_filteredParameters;
@property(readonly) DVTCrashPointAppStoreSource *appStoreSource; // @synthesize appStoreSource=_appStoreSource;
@property BOOL bypassCache; // @synthesize bypassCache=_bypassCache;
@property(nonatomic) BOOL bypassTimestampRestrictions; // @synthesize bypassTimestampRestrictions=_bypassTimestampRestrictions;
@property(retain) Class crashPointMoreLogsClass; // @synthesize crashPointMoreLogsClass=_crashPointMoreLogsClass;
@property(retain) Class crashPointDownloadDataClass; // @synthesize crashPointDownloadDataClass=_crashPointDownloadDataClass;
@property(retain) Class crashPointListClass; // @synthesize crashPointListClass=_crashPointListClass;
@property(readonly) DVTAnalyticsDownloadMoreLogsOptions *_defaultCrashPointMoreLogsOptions; // @synthesize _defaultCrashPointMoreLogsOptions;
- (void).cxx_destruct;
- (id)_requestMoreLogsForCrashPointIdentifier:(id)arg1 withSession:(id)arg2 options:(id)arg3 error:(id *)arg4;
- (id)_requestCrashPointForIdentifier:(id)arg1 withSession:(id)arg2 options:(id)arg3 error:(id *)arg4;
- (id)_requestCrashPointForIdentifier:(id)arg1 withSession:(id)arg2 error:(id *)arg3;
@property(readonly) DVTAnalyticsCrashPointDistributionOptions *_defaultCrashPointDownloadOptions; // @synthesize _defaultCrashPointDownloadOptions;
- (id)_requestTopCrashesListsForAppIdentifiers:(id)arg1 withSession:(id)arg2 options:(id)arg3;
- (id)_requestTopCrashesListsForAppIdentifiers:(id)arg1 withSession:(id)arg2;
- (id)_requestTopCrashesListForAppIdentifier:(id)arg1 withSession:(id)arg2 options:(id)arg3 error:(id *)arg4;
- (id)_requestTopCrashesListForAppIdentifier:(id)arg1 withSession:(id)arg2 error:(id *)arg3;
@property(readonly) NSArray *_defaultCrashPointListOptions; // @synthesize _defaultCrashPointListOptions;
- (BOOL)downloadMoreLogsForCrashPoint:(id)arg1 withSession:(id)arg2 error:(id *)arg3;
- (id)_crashLogsFromLogDataList:(id)arg1 cachePath:(id)arg2;
- (id)_fetchCrashPointDataForIdentifier:(id)arg1 fromNetworkWithSession:(id)arg2 error:(id *)arg3;
- (id)_fetchCrashPoinListFromNetworkWithSession:(id)arg1 error:(id *)arg2;
- (id)_invalidSelfError;
- (BOOL)refreshFromNetworkWithSession:(id)arg1 errors:(id *)arg2;
- (BOOL)refreshFromDiskWithError:(id *)arg1;
- (id)_webServiceLock;
@property(retain) NSDate *lastRefreshDate;
- (id)cachedPathForCrashPoint:(id)arg1;
- (void)primitiveInvalidate;
- (id)initWithParameters:(id)arg1 filter:(id)arg2 appStoreSource:(id)arg3 crashPointListClass:(Class)arg4 crashPointDownloadDataClass:(Class)arg5 crashPointMoreLogsClass:(Class)arg6;
- (id)initWithParameters:(id)arg1 filter:(id)arg2 appStoreSource:(id)arg3;
- (id)initWithBundleIdentifier:(id)arg1 version:(id)arg2 buildNumber:(id)arg3 isBeta:(BOOL)arg4;

// Remaining properties
@property(copy) NSArray *crashPoints; // @dynamic crashPoints;
@property(readonly, copy) NSMutableArray *mutableCrashPoints; // @dynamic mutableCrashPoints;

@end