//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTCrashLogParsedStackFrame : NSObject
{
    unsigned long long _depth;
    NSString *_image;
    NSString *_address;
    NSString *_symbol;
    unsigned long long _offset;
    NSString *_comment;
    NSString *_sourceFile;
    unsigned long long _sourceLine;
    NSString *_parserIdentifier;
}

@property(readonly) NSString *parserIdentifier; // @synthesize parserIdentifier=_parserIdentifier;
@property unsigned long long sourceLine; // @synthesize sourceLine=_sourceLine;
@property(retain) NSString *sourceFile; // @synthesize sourceFile=_sourceFile;
@property(retain) NSString *comment; // @synthesize comment=_comment;
@property unsigned long long offset; // @synthesize offset=_offset;
@property(retain) NSString *symbol; // @synthesize symbol=_symbol;
@property(retain) NSString *address; // @synthesize address=_address;
@property(retain) NSString *image; // @synthesize image=_image;
@property unsigned long long depth; // @synthesize depth=_depth;
- (void).cxx_destruct;
- (id)description;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithParserIdentifier:(id)arg1;

@end