//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTCrashLogThread : DVTCrashLogBacktrace
{
    BOOL _crashed;
    unsigned long long _number;
}

@property(readonly) BOOL crashed; // @synthesize crashed=_crashed;
@property(readonly) unsigned long long number; // @synthesize number=_number;
- (id)initWithName:(id)arg1 number:(unsigned long long)arg2 frames:(id)arg3 crashed:(BOOL)arg4;
- (id)initWithName:(id)arg1 frames:(id)arg2;

@end