//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SKEDocumentAddMaterialAtIndexEdition : SKEDocumentEdition
{
    SCNGeometry *_geometry;
    SCNMaterial *_material;
    unsigned long long _index;
}

- (void).cxx_destruct;
- (BOOL)revert;
- (BOOL)apply;
- (id)initWithDocument:(id)arg1 material:(id)arg2 index:(unsigned long long)arg3 geometry:(id)arg4;

@end