//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DevkitIdentifierExpression : DevkitExpression
{
    DevkitDeclaration *_identDecl;
}

- (void).cxx_destruct;
- (id)shortDescription;
- (id)description;
- (id)type;
- (id)prettyPrint;
- (id)declaration;
- (void)setDeclaration:(id)arg1;
- (void)cleanup;
- (id)init;

@end