//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IBICScreenWidth : IBICMultipartImageRepSlotComponent <NSCoding>
{
    double _minimumWidth;
    double _maximumWidth;
    long long _coreUISubtype;
}

+ (id)itemWithIdentifier:(id)arg1 fileNameComponent:(id)arg2 title:(id)arg3 minimumWidth:(double)arg4 maximumWidth:(double)arg5 coreUISubtype:(long long)arg6 displayOrder:(double)arg7;
+ (id)contentsJSONKey;
@property(readonly) long long coreUISubtype; // @synthesize coreUISubtype=_coreUISubtype;
@property(readonly) double maximumWidth; // @synthesize maximumWidth=_maximumWidth;
@property(readonly) double minimumWidth; // @synthesize minimumWidth=_minimumWidth;
- (void)ibic_appendAdditionalPseudoXMLAttrbutes:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (BOOL)isEqualToScreenWidth:(id)arg1;
- (id)initWithIdentifier:(id)arg1 fileNameComponent:(id)arg2 title:(id)arg3 minimumWidth:(double)arg4 maximumWidth:(double)arg5 coreUISubtype:(long long)arg6 displayOrder:(double)arg7;

@end