//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SimDeviceMenuItemPair : NSObject
{
    NSMenuItem *_primaryMenuItem;
    NSMenuItem *_alternateMenuItem;
}

@property(retain) NSMenuItem *alternateMenuItem; // @synthesize alternateMenuItem=_alternateMenuItem;
@property(retain) NSMenuItem *primaryMenuItem; // @synthesize primaryMenuItem=_primaryMenuItem;
- (void).cxx_destruct;

@end