//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVT__VMULibraryLoadObserver : NSObject
{
    id <DVT_VMULibraryLoadDelegate> _delegate;
    NSObject<OS_dispatch_queue> *_serialNotificationsQueue;
    struct _CSTypeRef _symbolicator;
}

- (void)stopObserving;
- (void)dealloc;
- (id)initWithTask:(unsigned int)arg1 delegate:(id)arg2;

@end