//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface GPUDebuggerLogProvider : IDELogProvider
{
    IDEWorkspace *_workspace;
    GPUSharedTabUIState *_sharedUIStateObj;
    DVTObservingToken *_launchSessionStateObserverToken;
    NSMapTable *_observerKeyForLaunchSessionTable;
    IDELogStore *_logStore;
    NSDictionary *_programInfoDict;
    GPUDebuggerLog *_debuggerLog;
}

+ (id)keyPathsForValuesAffectingLogRecords;
+ (id)_logStorePrefix;
- (void).cxx_destruct;
- (void)_handleProgramInfoLogCreated:(id)arg1 withLaunchSession:(id)arg2;
- (void)_handleLaunchSessionsChanged:(id)arg1;
- (void)_handleSyntheticLaunchSessionChange:(id)arg1;
- (void)_setupDebugAdditionObserversForLaunchSession:(id)arg1;
- (void)_removeDebugAdditionObserversForLaunchSession:(id)arg1;
- (id)logRecords;
- (void)primitiveInvalidate;
- (id)initWithDomainItem:(id)arg1;

@end