//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface GPUNavigatorStatusCell : IDENavigatorStatusCell
{
}

- (void)drawTextStatusWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)_drawStatusStringInPathRect:(struct CGRect)arg1 view:(id)arg2;
- (id)initWithType:(int)arg1;

@end