//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTCodesignResolver : NSObject
{
}

+ (id)parametersForIdentity:(id)arg1 profileUUID:(id)arg2 andBundleIdentifier:(id)arg3 platform:(id)arg4 requiredCodesignableDevices:(id)arg5 certificateUtilities:(id)arg6 withError:(id *)arg7;
+ (id)parametersForIdentity:(id)arg1 profileUUID:(id)arg2 andBundleIdentifier:(id)arg3 requiringProfile:(_Bool)arg4 platform:(id)arg5 requiredCodesignableDevices:(id)arg6 certificateUtilities:(id)arg7 withError:(id *)arg8;
+ (id)parametersForIdentity:(id)arg1 profileUUID:(id)arg2 andBundleIdentifier:(id)arg3 requiringProfile:(_Bool)arg4 limitSearchToKeychain:(struct OpaqueSecKeychainRef *)arg5 platform:(id)arg6 requiredCodesignableDevices:(id)arg7 certificateUtilities:(id)arg8 withError:(id *)arg9;
+ (id)parametersForTeamID:(id)arg1 certificateKind:(id)arg2 bundleIdentifier:(id)arg3 entitlements:(id)arg4 requiredFeatures:(id)arg5 limitSearchToKeychain:(struct OpaqueSecKeychainRef *)arg6 platform:(id)arg7 requiredCodesignableDevices:(id)arg8 requiresProfile:(_Bool)arg9 certificateUtilities:(id)arg10 withError:(id *)arg11;
+ (id)parametersForTeamID:(id)arg1 automaticIdentitySelector:(id)arg2 bundleIdentifier:(id)arg3 entitlements:(id)arg4 requiredFeatures:(id)arg5 limitSearchToKeychain:(struct OpaqueSecKeychainRef *)arg6 platform:(id)arg7 requiredCodesignableDevices:(id)arg8 requiresProfile:(_Bool)arg9 certificateUtilities:(id)arg10 withError:(id *)arg11;
+ (id)parametersForTeamID:(id)arg1 bundleIdentifier:(id)arg2 entitlements:(id)arg3 requiredFeatures:(id)arg4 applicableSigningIdentityCertificates:(id)arg5 platform:(id)arg6 requiredCodesignableDevices:(id)arg7 requiresProfile:(_Bool)arg8 profileManager:(id)arg9 logAspect:(id)arg10 withError:(id *)arg11;
+ (id)adHocProfileCodesignableDeviceSentinel;
+ (id)appStoreProfileCodesignableDeviceSentinel;
+ (id)parametersForInputs:(id)arg1 identity:(id)arg2 profileUUID:(id)arg3 limitSearchToKeychain:(struct OpaqueSecKeychainRef *)arg4 certificateUtilities:(id)arg5 withError:(id *)arg6;
+ (id)parametersForInputs:(id)arg1 identity:(id)arg2 profileUUID:(id)arg3 certificateUtilities:(id)arg4 withError:(id *)arg5;
+ (id)parametersForInputs:(id)arg1 identity:(id)arg2 limitSearchToKeychain:(struct OpaqueSecKeychainRef *)arg3 certificateUtilities:(id)arg4 withError:(id *)arg5;
+ (id)_identitySigningCertificatesInArray:(id)arg1 matchingIdentityString:(id)arg2 inputs:(id)arg3 withError:(id *)arg4;
+ (id)parametersForInputs:(id)arg1 applicableSigningIdentityCertificates:(id)arg2 profileManager:(id)arg3 logAspect:(id)arg4 withError:(id *)arg5;
+ (id)parametersForInputs:(id)arg1 limitSearchToKeychain:(struct OpaqueSecKeychainRef *)arg2 certificateUtilities:(id)arg3 withError:(id *)arg4;
+ (id)signingIdentityCertificatesForTeamID:(id)arg1 certificateKind:(id)arg2 keychainToSearchIn:(struct OpaqueSecKeychainRef *)arg3 certificateManager:(id)arg4;
+ (id)parametersForAdHocSigning;
+ (id)parametersForNullSigning;
+ (id)resolutionErrorWithCode:(long long)arg1 message:(id)arg2 recoverySuggestion:(id)arg3 inputs:(id)arg4;

@end