//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IBMacIdiom : IBIdiom
{
}

- (void)populateVariantForResolvingMediaResources:(id)arg1 forDocument:(id)arg2;
- (Class)storyboardCompilerClass;
- (Class)xibCompilerClass;
- (BOOL)usesSceneExitPlaceholder;
- (id)xibArchivingSchema;
- (id)storyboardArchivingSchema;
- (id)storyboardScenePasteboardType;
- (id)storyboardPrimarySceneObjectPasteboardType;
- (id)viewPasteboardType;
- (id)objectPasteboardType;
- (Class)storyboardMainEntryPointIndicatorClass;
- (Class)storyboardAssetProviderClass;
- (Class)xibAssetProviderClass;
- (Class)storyboardVerifierClass;
- (Class)xibVerifierClass;
- (double)defaultOverviewZoomFactor;
- (id)pluginName;
- (id)icon;
- (id)identifier;

@end