//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NSButton (IBNSButtonIntegration)
- (unsigned long long)ibOrientationsForSizingToFitFromLibrary;
- (void)ibVerifyFrameToControlSizeConsistency;
- (id)ibQualifyingInfoForDefaultLabel;
- (id)ibLocalAttributeKeyPaths;
- (id)ibInitialConnectionLabelSearchTerm;

// Remaining properties
@property(getter=isSpringLoaded) BOOL springLoaded;
@end