//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol IDELocalizationWorkReadStrings
@property(retain) NSDictionary *IDELocalizationWork_comments;
@property(retain) NSDictionary *IDELocalizationWork_strings;
@property(retain) DVTFilePath *IDELocalizationWork_path;
@end