//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NodeInfo : NSObject
{
    CDStruct_76845b71 *_info;
}

@property CDStruct_76845b71 *info; // @synthesize info=_info;
- (void)dealloc;
- (id)init;

@end