//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTArchiveProductSource : DVTProductSource
{
    IDEArchiveManager *_archiveManager;
    DVTObservingToken *_archivedProductsObservingToken;
    DVTDelayedInvocation *_updateArchivesDelayedInvocation;
}

@property(retain, nonatomic) DVTDelayedInvocation *updateArchivesDelayedInvocation; // @synthesize updateArchivesDelayedInvocation=_updateArchivesDelayedInvocation;
@property(retain) DVTObservingToken *archivedProductsObservingToken; // @synthesize archivedProductsObservingToken=_archivedProductsObservingToken;
@property(retain, nonatomic) IDEArchiveManager *archiveManager; // @synthesize archiveManager=_archiveManager;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (id)_productsFromArchives:(id)arg1 coordinator:(id)arg2;
- (id)mostRecentArchive:(id)arg1;
- (void)_addArchive:(id)arg1 toMalformedProductsDict:(id)arg2;
- (void)refreshProducts;
- (void)_startLocating;
- (id)initWithArchiveManager:(id)arg1 productManager:(id)arg2;
- (id)initWithProductManager:(id)arg1;

@end