//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTAppStoreProductSource : DVTProductSource
{
    DVTPerformanceMetric *_perfMetric;
    DVTFilePath *_productsRootDirectory;
    DVTDelayedInvocation *_delayedRefreshInvocation;
    DVTObservingToken *_developerAccountsObserver;
    NSSet *_developerAccountPasswordObservers;
}

+ (id)defaultProductsRootDirectory;
+ (BOOL)isAdamIdWhitelisted:(id)arg1;
+ (id)whiteListedAppByAdamId;
@property(retain) NSSet *developerAccountPasswordObservers; // @synthesize developerAccountPasswordObservers=_developerAccountPasswordObservers;
@property(retain) DVTObservingToken *developerAccountsObserver; // @synthesize developerAccountsObserver=_developerAccountsObserver;
@property(retain, nonatomic) DVTDelayedInvocation *delayedRefreshInvocation; // @synthesize delayedRefreshInvocation=_delayedRefreshInvocation;
@property(retain, nonatomic) DVTFilePath *productsRootDirectory; // @synthesize productsRootDirectory=_productsRootDirectory;
- (void).cxx_destruct;
- (id)_binaryInfoForVersion:(id)arg1;
- (id)_productVersionForExtension:(id)arg1 productType:(unsigned long long)arg2 adamId:(id)arg3 appStoreStatus:(unsigned long long)arg4 supportedDeviceTypes:(id)arg5 supportedOSVersions:(id)arg6;
- (id)_supportedDeviceTypesForAppVersion:(id)arg1 productType:(unsigned long long)arg2;
- (id)_symbolInfoForVersion:(id)arg1 session:(id)arg2 error:(id *)arg3;
- (id)_productFromAppDescription:(id)arg1 versionDescriptions:(id)arg2 session:(id)arg3 coordinator:(id)arg4 errors:(id *)arg5;
- (id)_productsForAccount:(id)arg1 coordinator:(id)arg2;
- (id)_productsFromITunesWithCoordinator:(id)arg1;
- (void)_setBusyOnMainThread:(BOOL)arg1;
- (void)_delayedRefreshProducts;
- (void)refreshProducts;
- (void)_startLocating;
- (BOOL)_networkRefreshEnabled;
- (id)_resultByMergingProductResults:(id)arg1 withCoordinator:(id)arg2;
- (id)updateCacheWithResult:(id)arg1;
- (id)readProductsFromCacheWithCoordinator:(id)arg1;
- (id)appIconPathForProduct:(id)arg1;
- (id)filePathForProduct:(id)arg1 withVersion:(id)arg2 andBuild:(id)arg3;
- (id)filePathForProduct:(id)arg1;
- (id)_cacheAndNetworkLock;
- (void)primitiveInvalidate;
- (id)initWithProductManager:(id)arg1 productsRootDirectory:(id)arg2;
- (id)initWithProductManager:(id)arg1;

@end