//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTMalformedProduct : DVTProduct <NSCopying>
{
    NSArray *_archives;
}

+ (id)productByMergingProducts:(id)arg1 coordinator:(id)arg2;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)name;
- (id)archives;
- (id)_initWithCoordinator:(id)arg1 productIdentifier:(id)arg2 productVersions:(id)arg3;
- (id)_initWithCoordinator:(id)arg1 archives:(id)arg2;

@end