//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTProductsClientSessionAssistant : NSObject
{
    DVTDeveloperAccount *_developerAccount;
    NSString *_developerAccountUser;
}

@property(retain) NSString *developerAccountUser; // @synthesize developerAccountUser=_developerAccountUser;
@property(retain, nonatomic) DVTDeveloperAccount *developerAccount; // @synthesize developerAccount=_developerAccount;
- (void).cxx_destruct;
- (id)sessionWithError:(id *)arg1;
- (id)initWithDeveloperAccountUser:(id)arg1;
- (id)init;

@end