//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTProductVersionSymbolInfo : NSObject <DVTServicesJSONSerialization>
{
    NSDictionary *_uuidToSymbolURL;
}

+ (id)objectFromJSONRepresentation:(id)arg1 error:(id *)arg2;
@property(readonly) NSDictionary *uuidToSymbolURL; // @synthesize uuidToSymbolURL=_uuidToSymbolURL;
- (void).cxx_destruct;
- (id)JSONRepresentation;
- (BOOL)containsUUID:(id)arg1;
- (id)symbolURLForUUID:(id)arg1;
- (id)UUIDs;
@property(readonly) unsigned long long hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithUUIDToSymbolURLDictionary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end