//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTProductIdentifier : NSObject <DVTServicesJSONSerialization, NSCopying>
{
    NSString *_bundleIdentifier;
    unsigned long long _productType;
}

+ (id)objectFromJSONRepresentation:(id)arg1 error:(id *)arg2;
+ (id)productIdentifierForArchive:(id)arg1;
+ (id)productIdentifierWithBundleIdentifier:(id)arg1 productType:(unsigned long long)arg2;
@property(readonly) unsigned long long productType; // @synthesize productType=_productType;
@property(readonly) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
- (void).cxx_destruct;
- (id)JSONRepresentation;
- (id)descriptionForUserDefaultsKeyWithError:(id *)arg1;
@property(readonly) NSString *stringRepresentation;
@property(readonly, copy) NSString *description;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly) unsigned long long hash;
- (BOOL)isEqual:(id)arg1;
- (long long)compare:(id)arg1;
- (id)initWithBundleIdentifier:(id)arg1 productType:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end