//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEArchive (Products)
+ (id)largestImageInFilePaths:(id)arg1;
@property(readonly) NSNumber *products_onDiskSizeBytes;
@property(readonly) unsigned long long products_productType;
@property(readonly) NSURL *products_imageURL;
- (id)products_platformName;
- (id)products_appInfoPlist;
@property(readonly) NSString *products_displayName;
- (id)_products_appInfoPlist;
@end