//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEMockArchive : IDEArchive
{
    NSString *_schemeName;
}

@property(retain) NSString *schemeName; // @synthesize schemeName=_schemeName;
- (void).cxx_destruct;
- (unsigned long long)products_productType;

@end