//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface _DVTCrashLogTopPaddingView : NSView
{
}

- (void)drawRect:(struct CGRect)arg1;

@end