//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTCrashChartScaffoldView : NSView
{
    NSColor *_debugColor;
}

@property(copy) NSColor *debugColor; // @synthesize debugColor=_debugColor;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;

@end