//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTCrashPoint (TableCellAttributes)
+ (id)keyPathsForValuesAffectingCrashPointSubtitle;
+ (id)keyPathsForValuesAffectingCrashPointTitle;
+ (id)keyPathsForValuesAffectingResolvedImage;
- (id)attributedStringWithAppropriateColor:(id)arg1;
- (id)textAttributes;
- (id)unresolvedAttributes;
- (id)resolvedAttributes;
- (id)crashPointSubtitle;
- (id)crashPointTitle;
- (id)resolvedImage;
@end