//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTCrashPoint (DebuggerIntegration)
- (long long)crashPointStringMatchesStackFrame:(id)arg1;
- (id)ideCrashPointForWorkspace:(id)arg1 productVersion:(id)arg2 error:(id *)arg3;
@end