//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTCrashChartView_ViewData : NSObject
{
    NSString *_label;
    NSNumber *_rawValue;
    NSString *_displayValue;
    double _relativeValueToDataSeries;
    NSColor *_color;
}

@property(copy, nonatomic) NSColor *color; // @synthesize color=_color;
@property(nonatomic) double relativeValueToDataSeries; // @synthesize relativeValueToDataSeries=_relativeValueToDataSeries;
@property(copy, nonatomic) NSString *displayValue; // @synthesize displayValue=_displayValue;
@property(copy, nonatomic) NSNumber *rawValue; // @synthesize rawValue=_rawValue;
@property(copy, nonatomic) NSString *label; // @synthesize label=_label;
- (void).cxx_destruct;
- (id)initWithLabel:(id)arg1 rawValue:(id)arg2 color:(id)arg3;

@end