//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTCrashChartDistributionTable : DVTCrashChartScaffoldView
{
    NSArray *_dataSet;
}

@property(copy, nonatomic) NSArray *dataSet; // @synthesize dataSet=_dataSet;
- (void).cxx_destruct;
- (BOOL)isFlipped;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end