//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTCrashLogParsedStackFrame (UIAdditions)
+ (id)_genericFrameImageIsCrash:(BOOL)arg1;
+ (id)_createImageFromFilePath:(id)arg1 withRed:(float)arg2 green:(float)arg3 blue:(float)arg4 alpha:(float)arg5 isRecorded:(BOOL)arg6 isCrash:(BOOL)arg7;
@property(readonly, copy, nonatomic) NSArray *allFindHighlightRanges;
@property(retain, nonatomic) NSArray *imageTextFindMatchingSubranges; // @dynamic imageTextFindMatchingSubranges;
@property(retain, nonatomic) NSArray *frameTextFindMatchingSubranges; // @dynamic frameTextFindMatchingSubranges;
- (BOOL)ide_hasSymbolsWithAppName:(id)arg1;
- (BOOL)ide_isCrashedFrameInCrashPoint:(id)arg1;
- (id)ide_presentableImageWithAppName:(id)arg1 forCrashPoint:(id)arg2;
@end