//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDECrashPointOpenInProjectSheetController : NSWindowController <DVTInvalidation>
{
    DVTFilePath *_projectFilePath;
    IDECrashPointOpenInProjectViewController *_openInProjectViewController;
}

+ (void)initialize;
@property(retain) IDECrashPointOpenInProjectViewController *openInProjectViewController; // @synthesize openInProjectViewController=_openInProjectViewController;
@property(retain) DVTFilePath *projectFilePath; // @synthesize projectFilePath=_projectFilePath;
- (void).cxx_destruct;
- (void)beginSheetModalForWindow:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)windowDidLoad;
@property(readonly) NSURL *projectURL;
- (void)primitiveInvalidate;
- (id)init;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end