//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDECrashPointTranslationContext : NSObject
{
    DVTCrashPoint *_crashPoint;
    IDEWorkspace *_workspace;
    NSSet *_binaryUUIDsWithSymbols;
    NSMutableDictionary *_fileNameToFilePathMap;
    NSMutableDictionary *_codeModulesByName;
}

@property(retain) NSMutableDictionary *codeModulesByName; // @synthesize codeModulesByName=_codeModulesByName;
@property(retain) NSMutableDictionary *fileNameToFilePathMap; // @synthesize fileNameToFilePathMap=_fileNameToFilePathMap;
@property(retain) NSSet *binaryUUIDsWithSymbols; // @synthesize binaryUUIDsWithSymbols=_binaryUUIDsWithSymbols;
@property __weak IDEWorkspace *workspace; // @synthesize workspace=_workspace;
@property(retain) DVTCrashPoint *crashPoint; // @synthesize crashPoint=_crashPoint;
- (void).cxx_destruct;
- (id)codeModuleForName:(id)arg1;
- (void)setCodeModule:(id)arg1 forName:(id)arg2 passesBuildProductDirFallback:(BOOL)arg3;
- (BOOL)hasSymbolsForBinaryWithUUID:(id)arg1;
- (id)filePathForFileName:(id)arg1;
- (id)initWithCrashPoint:(id)arg1 workspace:(id)arg2 binaryUUIDsWithSymbols:(id)arg3;

@end