//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDECrashPointSourceListViewController : IDEViewController <IDEFilterControlBarTarget, DVTTableViewDelegate, NSMenuDelegate>
{
    BOOL _busy;
    BOOL _restoringSelectedCrashPoint;
    BOOL _updatingCrashPointsForDisplay;
    IDECrashPointsViewController *_crashPointsViewController;
    DVTCrashPoint *_selectedCrashPoint;
    IDECrashPointSourceSelector *_sourceSelector;
    NSIndexSet *_crashPointsTableSelectionIndexes;
    NSArrayController *_crashPointsController;
    DVTTableView *_crashPointsTableView;
    NSScrollView *_crashPointsTableScrollView;
    DVTBorderedView *_crashPointsBorderedView;
    IDEFilterControlBar *_crashPointsFilterControlBar;
    DVTBorderedView *_borderedView;
    DVTBorderedView *_crashPointSourceSelectorBorder;
    NSString *_searchString;
    DVTDispatchLock *_crashPointSourceLock;
    DVTDelayedInvocation *_delayedUpdateCrashPointsInvocation;
    NSArray *_crashPointsForDisplay;
    DVTUserDefaultsLeastRecentlyUsedCache *_selectedCrashPointCache;
    DVTObservingToken *_selectedObjectsObservingToken;
    DVTObservingToken *_selectedProductObservingToken;
    DVTObservingToken *_selectedCrashPointSourceObservingToken;
    DVTObservingToken *_crashPointsObserver;
}

+ (id)keyPathsForValuesAffectingSelectedCrashPointSource;
+ (id)keyPathsForValuesAffectingCrashPointsFilterPredicate;
@property(retain) DVTObservingToken *crashPointsObserver; // @synthesize crashPointsObserver=_crashPointsObserver;
@property(retain) DVTObservingToken *selectedCrashPointSourceObservingToken; // @synthesize selectedCrashPointSourceObservingToken=_selectedCrashPointSourceObservingToken;
@property(retain) DVTObservingToken *selectedProductObservingToken; // @synthesize selectedProductObservingToken=_selectedProductObservingToken;
@property(retain) DVTObservingToken *selectedObjectsObservingToken; // @synthesize selectedObjectsObservingToken=_selectedObjectsObservingToken;
@property(getter=isUpdatingCrashPointsForDisplay) BOOL updatingCrashPointsForDisplay; // @synthesize updatingCrashPointsForDisplay=_updatingCrashPointsForDisplay;
@property(getter=isRestoringSelectedCrashPoint) BOOL restoringSelectedCrashPoint; // @synthesize restoringSelectedCrashPoint=_restoringSelectedCrashPoint;
@property(retain) DVTUserDefaultsLeastRecentlyUsedCache *selectedCrashPointCache; // @synthesize selectedCrashPointCache=_selectedCrashPointCache;
@property(retain) NSArray *crashPointsForDisplay; // @synthesize crashPointsForDisplay=_crashPointsForDisplay;
@property(retain) DVTDelayedInvocation *delayedUpdateCrashPointsInvocation; // @synthesize delayedUpdateCrashPointsInvocation=_delayedUpdateCrashPointsInvocation;
@property(retain, nonatomic) DVTDispatchLock *crashPointSourceLock; // @synthesize crashPointSourceLock=_crashPointSourceLock;
@property(copy) NSString *searchString; // @synthesize searchString=_searchString;
@property __weak DVTBorderedView *crashPointSourceSelectorBorder; // @synthesize crashPointSourceSelectorBorder=_crashPointSourceSelectorBorder;
@property __weak DVTBorderedView *borderedView; // @synthesize borderedView=_borderedView;
@property __weak IDEFilterControlBar *crashPointsFilterControlBar; // @synthesize crashPointsFilterControlBar=_crashPointsFilterControlBar;
@property __weak DVTBorderedView *crashPointsBorderedView; // @synthesize crashPointsBorderedView=_crashPointsBorderedView;
@property __weak NSScrollView *crashPointsTableScrollView; // @synthesize crashPointsTableScrollView=_crashPointsTableScrollView;
@property __weak DVTTableView *crashPointsTableView; // @synthesize crashPointsTableView=_crashPointsTableView;
@property __weak NSArrayController *crashPointsController; // @synthesize crashPointsController=_crashPointsController;
@property(retain, nonatomic) NSIndexSet *crashPointsTableSelectionIndexes; // @synthesize crashPointsTableSelectionIndexes=_crashPointsTableSelectionIndexes;
@property(getter=isBusy) BOOL busy; // @synthesize busy=_busy;
@property(retain) IDECrashPointSourceSelector *sourceSelector; // @synthesize sourceSelector=_sourceSelector;
@property(retain) DVTCrashPoint *selectedCrashPoint; // @synthesize selectedCrashPoint=_selectedCrashPoint;
@property(readonly) __weak IDECrashPointsViewController *crashPointsViewController; // @synthesize crashPointsViewController=_crashPointsViewController;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 rowViewForRow:(long long)arg2;
- (BOOL)tableView:(id)arg1 shouldSelectRow:(long long)arg2;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (BOOL)_isRowBeforeGroupRow:(unsigned long long)arg1;
- (BOOL)_isGroupRow:(unsigned long long)arg1;
- (id)_previousTopCrashesAttributedTitle;
- (void)refresh;
- (void)_updateCrashPointsFromNetworkWithCallback:(CDUnknownBlockType)arg1;
- (void)_updateCrashPointsFromCacheWithCallback:(CDUnknownBlockType)arg1;
- (id)_appStoreCrashPointSource;
- (BOOL)_shouldRefreshFromNetwork;
- (void)_setBusyOnMainThread:(BOOL)arg1;
- (void)_updateCrashPointSourceData;
- (void)_restoreCrashPointSourceListScrollPosition;
- (void)_restoreSelectedCrashPoint;
- (void)_saveSelectedCrashPoint;
- (void)_updateCrashPointsForDisplay;
- (void)productsContextMenu_showCrashPointInFinder:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (id)crashPointsFilterPredicate;
@property(readonly) DVTCrashPointSource *selectedCrashPointSource;
@property BOOL showsUnresolvedCrashPointsOnly;
- (id)filterButtonMenu;
- (id)filterDefinitionIdentifier;
- (id)selectedCrashPointFromSelectedIndex:(id)arg1;
- (void)viewDidInstall;
- (void)loadView;
- (void)primitiveInvalidate;
- (id)initWithCrashPointsViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end