//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDECrashPointOpenInProjectViewController : IDEViewController <DVTTableViewDelegate>
{
    NSURL *_projectURL;
    DVTBorderedView *_tableBorder;
    DVTTableView *_projectsTable;
    NSProgressIndicator *_spinner;
    DVTSearchField *_filterField;
    NSArrayController *_projectsController;
    IDERecentsHelper *_recentsHelper;
    DVTObservingToken *_selectionObserver;
    NSString *_searchString;
}

@property(retain, nonatomic) NSString *searchString; // @synthesize searchString=_searchString;
@property(retain) DVTObservingToken *selectionObserver; // @synthesize selectionObserver=_selectionObserver;
@property(retain) IDERecentsHelper *recentsHelper; // @synthesize recentsHelper=_recentsHelper;
@property(retain) NSArrayController *projectsController; // @synthesize projectsController=_projectsController;
@property __weak DVTSearchField *filterField; // @synthesize filterField=_filterField;
@property __weak NSProgressIndicator *spinner; // @synthesize spinner=_spinner;
@property __weak DVTTableView *projectsTable; // @synthesize projectsTable=_projectsTable;
@property __weak DVTBorderedView *tableBorder; // @synthesize tableBorder=_tableBorder;
@property(retain) NSURL *projectURL; // @synthesize projectURL=_projectURL;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (void)tableDoubleClicked:(id)arg1;
- (void)browse:(id)arg1;
- (void)cancel:(id)arg1;
- (void)open:(id)arg1;
- (void)_updateEmptyContentString;
- (void)_showBusy:(BOOL)arg1;
- (void)primitiveInvalidate;
- (void)viewDidAppear;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end