//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDECrashPointOverviewViewController : IDEViewController
{
    IDECrashPointDetailViewController *_detailViewController;
    DVTCrashPoint *_crashPoint;
    NSButton *_resolvedButton;
}

@property __weak NSButton *resolvedButton; // @synthesize resolvedButton=_resolvedButton;
@property(retain) DVTCrashPoint *crashPoint; // @synthesize crashPoint=_crashPoint;
@property __weak IDECrashPointDetailViewController *detailViewController; // @synthesize detailViewController=_detailViewController;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (void)viewDidLoad;

@end