//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDECrashPointLogViewController : IDEViewController <NSOutlineViewDataSource, NSOutlineViewDelegate, DVTReplacementViewDelegate>
{
    IDECrashPointDetailViewController *_detailViewController;
    DVTCrashLogRecord *_crashLogRecord;
    DVTCrashPoint *_crashPoint;
    NSOutlineView *_outlineView;
    DVTReplacementView *_replacementView;
}

@property __weak DVTReplacementView *replacementView; // @synthesize replacementView=_replacementView;
@property __weak NSOutlineView *outlineView; // @synthesize outlineView=_outlineView;
@property(retain, nonatomic) DVTCrashPoint *crashPoint; // @synthesize crashPoint=_crashPoint;
@property(retain, nonatomic) DVTCrashLogRecord *crashLogRecord; // @synthesize crashLogRecord=_crashLogRecord;
@property __weak IDECrashPointDetailViewController *detailViewController; // @synthesize detailViewController=_detailViewController;
- (void).cxx_destruct;
- (void)replacementView:(id)arg1 didInstallViewController:(id)arg2;
- (void)_updateInstalledViewController;
- (void)_updateLogView;
@property(readonly) DVTCrashLogViewController *crashLogViewController;
- (void)loadView;
- (void)primitiveInvalidate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end