//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEProductsButtonCell : NSButtonCell
{
}

- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;
- (id)attributedTitle;
- (void)drawBezelWithFrame:(struct CGRect)arg1 inView:(id)arg2;

@end