//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEProductsWindowController : NSWindowController <NSToolbarDelegate>
{
    NSSegmentedControl *_segmentControl;
    IDEProductsViewController *_productsViewController;
    NSToolbarItem *_segmentControlToolbarItem;
}

+ (id)sharedProductsWindowController;
@property __weak NSToolbarItem *segmentControlToolbarItem; // @synthesize segmentControlToolbarItem=_segmentControlToolbarItem;
@property(retain) IDEProductsViewController *productsViewController; // @synthesize productsViewController=_productsViewController;
@property __weak NSSegmentedControl *segmentControl; // @synthesize segmentControl=_segmentControl;
- (void).cxx_destruct;
- (void)_configureSegmentedControl;
- (id)showProductsSectionWithIdentifier:(id)arg1 forProductIdentifier:(id)arg2;
- (void)refresh;
- (void)resizeSegmentControl;
- (void)windowWillClose:(id)arg1;
- (void)showWindow:(id)arg1;
- (void)windowDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end