//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEProductsBillboardUtilityPane : IDEProductsUtilityPane
{
    NSString *_nameKeyPath;
    NSString *_subtitleKeyPath;
    NSString *_iconKeyPath;
    NSTextField *_titleField;
    NSTextField *_subtitleField;
    NSImageView *_imageView;
}

@property(retain) NSImageView *imageView; // @synthesize imageView=_imageView;
@property(retain) NSTextField *subtitleField; // @synthesize subtitleField=_subtitleField;
@property(retain) NSTextField *titleField; // @synthesize titleField=_titleField;
@property(retain, nonatomic) NSString *iconKeyPath; // @synthesize iconKeyPath=_iconKeyPath;
@property(retain, nonatomic) NSString *subtitleKeyPath; // @synthesize subtitleKeyPath=_subtitleKeyPath;
@property(retain, nonatomic) NSString *nameKeyPath; // @synthesize nameKeyPath=_nameKeyPath;
- (void).cxx_destruct;
- (void)bindIcon;
- (void)bindSubtitle;
- (void)bindName;
- (void)primitiveInvalidate;
- (void)loadView;

@end