//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol IDEProductsInspectableVending <NSObject>
@property(readonly) id <IDEProductsInspectable> currentInspectable;
@property(readonly) BOOL shouldShowNoSelection;
- (void)handleAction:(NSString *)arg1 fromInspectable:(id <IDEProductsInspectable>)arg2;
@end