//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEProductsUtilityViewController : IDEViewController
{
    id <IDEProductsInspectable> _inspectable;
    id <IDEProductsInspectableVending> _inspectableVendor;
    DVTBorderedView *_topBorderedView;
    DVTStackView_AppKitAutolayout *_infoPaneStackView;
    NSScrollView *_infoPaneScrollView;
    DVTBorderedView *_borderedView;
    NSTextField *_typeTextField;
    DVTObservingToken *_currentInspectableObservingToken;
}

+ (id)keyPathsForValuesAffectingShouldShowEmptyMessage;
+ (id)utilityPaneExtensionForIdentifier:(id)arg1;
+ (id)utilityExtensionForIdentifier:(id)arg1;
@property(retain) DVTObservingToken *currentInspectableObservingToken; // @synthesize currentInspectableObservingToken=_currentInspectableObservingToken;
@property __weak NSTextField *typeTextField; // @synthesize typeTextField=_typeTextField;
@property __weak DVTBorderedView *borderedView; // @synthesize borderedView=_borderedView;
@property __weak NSScrollView *infoPaneScrollView; // @synthesize infoPaneScrollView=_infoPaneScrollView;
@property __weak DVTStackView_AppKitAutolayout *infoPaneStackView; // @synthesize infoPaneStackView=_infoPaneStackView;
@property __weak DVTBorderedView *topBorderedView; // @synthesize topBorderedView=_topBorderedView;
@property(retain, nonatomic) id <IDEProductsInspectableVending> inspectableVendor; // @synthesize inspectableVendor=_inspectableVendor;
@property(retain, nonatomic) id <IDEProductsInspectable> inspectable; // @synthesize inspectable=_inspectable;
- (void).cxx_destruct;
- (id)_customPaneWithExtension:(id)arg1;
- (id)_descriptionPaneWithExtension:(id)arg1;
- (id)_detailPaneWithExtension:(id)arg1;
- (id)_doubleButtonPaneWithButtons:(id)arg1;
- (id)_singleButtonPaneWithButton:(id)arg1 primary:(BOOL)arg2;
- (id)_buttonPaneWithExtension:(id)arg1;
- (void)_updateLayout;
@property(readonly, nonatomic) BOOL shouldShowEmptyMessage;
- (void)primitiveInvalidate;
- (void)loadView;

@end