//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTLandmarkItemSwift : DVTSourceLandmarkItem
{
    shared_ptr_99585c3b _sharedItemRef;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithItemReference:(shared_ptr_99585c3b)arg1 type:(int)arg2 delegate:(id)arg3;

@end