//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEDocumentationPlaygroundSectionViewController : IDEViewController <IDEPlaygroundSectionViewController>
{
    BOOL _finishedLoading;
    BOOL _sizingToContent;
    IDEPlaygroundEditor *_playgroundEditor;
    IDEDocumentationPlaygroundSection *_playgroundSection;
    WebView *_webView;
    DVTNotificationToken *_webHTMLViewFrameChangeNotificationToken;
    DVTNotificationToken *_webViewFrameChangeNotificationToken;
    DVTNotificationToken *_fontAndColorSettingsChangedNotificationToken;
    DVTObservingToken *_accessoryAnnotationWidthObservingToken;
    DVTObservingToken *_quarantinedDocumentObservingToken;
}

+ (void)initialize;
@property BOOL sizingToContent; // @synthesize sizingToContent=_sizingToContent;
@property(retain) DVTObservingToken *quarantinedDocumentObservingToken; // @synthesize quarantinedDocumentObservingToken=_quarantinedDocumentObservingToken;
@property(retain) DVTObservingToken *accessoryAnnotationWidthObservingToken; // @synthesize accessoryAnnotationWidthObservingToken=_accessoryAnnotationWidthObservingToken;
@property(retain) DVTNotificationToken *fontAndColorSettingsChangedNotificationToken; // @synthesize fontAndColorSettingsChangedNotificationToken=_fontAndColorSettingsChangedNotificationToken;
@property(retain) DVTNotificationToken *webViewFrameChangeNotificationToken; // @synthesize webViewFrameChangeNotificationToken=_webViewFrameChangeNotificationToken;
@property(retain) DVTNotificationToken *webHTMLViewFrameChangeNotificationToken; // @synthesize webHTMLViewFrameChangeNotificationToken=_webHTMLViewFrameChangeNotificationToken;
@property(retain) WebView *webView; // @synthesize webView=_webView;
@property(retain) IDEDocumentationPlaygroundSection *playgroundSection; // @synthesize playgroundSection=_playgroundSection;
@property BOOL finishedLoading; // @synthesize finishedLoading=_finishedLoading;
@property(readonly) IDEPlaygroundEditor *playgroundEditor; // @synthesize playgroundEditor=_playgroundEditor;
- (void).cxx_destruct;
- (id)webView:(id)arg1 resource:(id)arg2 willSendRequest:(id)arg3 redirectResponse:(id)arg4 fromDataSource:(id)arg5;
- (void)primitiveInvalidate;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 request:(id)arg3 frame:(id)arg4 decisionListener:(id)arg5;
- (id)webView:(id)arg1 contextMenuItemsForElement:(id)arg2 defaultMenuItems:(id)arg3;
- (void)webView:(id)arg1 didFinishLoadForFrame:(id)arg2;
- (void)loadView;
- (id)_htmlPostamble;
- (id)_htmlPreamble;
- (void)_sizeToDoc;
- (id)initWithDocumentationPlaygroundSection:(id)arg1 editor:(id)arg2;

// Remaining properties
@property(readonly) NSArray *currentSelectedDocumentLocations;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end