//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEIBSwiftEventSourceCodeConnectionContext : IBObjCCocoaTouchEventConnectionContext
{
}

+ (id)eventType;
+ (id)floatType;
+ (id)boolType;
+ (id)defaultType;
+ (Class)sourceCodeGeneratorClass;
- (id)sourceCodeInsertionOptions;
- (id)representativeCounterpart;
- (BOOL)parseSourceLandmarkItem:(id)arg1;
- (id)containingClassName;
- (id)qualifiedType;

@end