//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEPlayground : IDEContainer <IDECustomDataStoring, IDEWorkspaceWrappingContainer, IDEBuildSettingsProvidingContainer>
{
    DVTObservingToken *_auxiliarySourceFolderObservingToken;
    double _playgroundWrapperLastModDate;
    IDEPlaygroundDocumentSharedContext *_playgroundContext;
    IDEDirectoryBasedCustomDataStore *_customDataStore;
    IDEContainerQuery *_auxSourceContainerQuery;
}

+ (id)containerTypeDisplayName;
+ (id)containerFileDataType;
+ (id)basicBuildFlagsForSources:(id)arg1 SDK:(id)arg2 target:(id)arg3;
+ (id)containerProvidedBuildSettingsForFile:(id)arg1;
+ (id)_playgroundContainerContainingAuxiliarySourceFile:(id)arg1;
+ (id)_sharedFilePathToPlaygroundMapTable;
+ (BOOL)isSourcesDirectorySubPath:(id)arg1;
@property(retain) IDEContainerQuery *auxSourceContainerQuery; // @synthesize auxSourceContainerQuery=_auxSourceContainerQuery;
@property(retain) IDEDirectoryBasedCustomDataStore *customDataStore; // @synthesize customDataStore=_customDataStore;
@property(retain) IDEPlaygroundDocumentSharedContext *playgroundContext; // @synthesize playgroundContext=_playgroundContext;
- (void).cxx_destruct;
- (void)_customDataStoreContainerClosing:(id)arg1;
- (BOOL)supportsCustomDataForOwnership:(id)arg1;
- (void)moveCustomDataWithSpecifier:(id)arg1 toSpecifier:(id)arg2 completionQueue:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (void)removeCustomDataWithSpecifier:(id)arg1 completionQueue:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)writeCustomData:(id)arg1 withSpecifier:(id)arg2 forceOverwrite:(BOOL)arg3 completionQueue:(id)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (id)readCustomDataWithSpecifier:(id)arg1 error:(id *)arg2;
- (id)customDataOwnershipsForGrouping:(id)arg1;
- (id)customDataSpecifiersForGrouping:(id)arg1 ownership:(id)arg2;
- (void)addSpecifier:(id)arg1 inWorkspace:(id)arg2 toSCMWithCompletionBlock:(CDUnknownBlockType)arg3;
- (void)scmStatusForSpecifier:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)becomeWorkspaceWrappingContainer;
@property(readonly) NSSet *sourcesDirectorySwiftFiles;
- (id)ide_defaultNewFileTemplateForPath:(id)arg1;
- (BOOL)_shouldRespondToFileChangeOnDisk;
- (id)createRootGroup;
- (void)_startTrackingAuxiliarySources;
- (void)primitiveInvalidate;
- (id)initWithFilePath:(id)arg1 extension:(id)arg2 workspace:(id)arg3 options:(id)arg4 error:(id *)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) NSString *displayName;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end