//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol IDEPlaygroundLoggerLogEntry <NSObject>
@property(readonly, copy) NSString *summary;
@property(readonly, copy) NSString *name;
@end