//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEPlaygroundQuickLookForBezierPath : IDEBasicPlaygroundQuickLookForObjectReflection
{
    DVTPathView *_pathView;
}

@property __weak DVTPathView *pathView; // @synthesize pathView=_pathView;
- (void).cxx_destruct;
- (id)quickLookViewForNaturalSize;
- (id)initWithObjectReflection:(id)arg1;

@end