//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEPlaygroundDocumentSharedContext : NSObject
{
    DVTFilePath *_filePath;
    DVTVersion *_documentVersion;
    NSString *_targetPlatformIdentifier;
    DVTSDK *_sdk;
}

+ (id)keyPathsForValuesAffectingTargetTriple;
+ (id)keyPathsForValuesAffectingDocumentVersionSupportsAuxiliarySources;
+ (id)keyPathsForValuesAffectingSdk;
+ (id)keyPathsForValuesAffectingSourcesDirectoryPath;
+ (id)keyPathsForValuesAffectingResourcesDirectoryPath;
+ (id)sharedPlaygroundContextForFilePath:(id)arg1;
@property(retain, nonatomic) DVTSDK *sdk; // @synthesize sdk=_sdk;
@property(copy, nonatomic) NSString *targetPlatformIdentifier; // @synthesize targetPlatformIdentifier=_targetPlatformIdentifier;
@property(copy, nonatomic) DVTVersion *documentVersion; // @synthesize documentVersion=_documentVersion;
@property(nonatomic) __weak DVTFilePath *filePath; // @synthesize filePath=_filePath;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *targetTriple;
@property(readonly) BOOL documentVersionSupportsAuxiliarySources;
@property(readonly, nonatomic) DVTFilePath *sourcesDirectoryPath;
@property(readonly, nonatomic) DVTFilePath *resourcesDirectoryPath;
- (id)description;
- (void)_readAndSetDocumentMetadataForFilePath:(id)arg1;

@end