//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEPlaygroundAuxiliarySourceCompiler : DVTOperation
{
    BOOL _compilerLoggingEnabled;
    DVTFilePath *_playgroundFilePath;
    DVTFilePath *_sourcesDirectoryFilePath;
    NSSet *_sourcesDirectorySwiftFiles;
    DVTFilePath *_playgroundPath;
    DVTFilePath *_resourcesDirectory;
    DVTSDK *_sdk;
    NSString *_target;
    DVTFilePath *_buildProductsPath;
    NSString *_sourcesModuleName;
    IDEActivityLogSection *_activityLogSection;
    DVTTask *_compilerTask;
}

+ (id)sourcesModuleNameForPlayground:(id)arg1;
+ (id)logAspect;
@property(retain) DVTTask *compilerTask; // @synthesize compilerTask=_compilerTask;
@property(retain) IDEActivityLogSection *activityLogSection; // @synthesize activityLogSection=_activityLogSection;
@property(readonly, copy) NSString *sourcesModuleName; // @synthesize sourcesModuleName=_sourcesModuleName;
@property(copy) DVTFilePath *buildProductsPath; // @synthesize buildProductsPath=_buildProductsPath;
@property(copy) NSString *target; // @synthesize target=_target;
@property(retain) DVTSDK *sdk; // @synthesize sdk=_sdk;
@property(copy) DVTFilePath *resourcesDirectory; // @synthesize resourcesDirectory=_resourcesDirectory;
@property(readonly, copy) DVTFilePath *playgroundPath; // @synthesize playgroundPath=_playgroundPath;
@property(readonly, copy) NSSet *sourcesDirectorySwiftFiles; // @synthesize sourcesDirectorySwiftFiles=_sourcesDirectorySwiftFiles;
@property(copy) DVTFilePath *sourcesDirectoryFilePath; // @synthesize sourcesDirectoryFilePath=_sourcesDirectoryFilePath;
@property(copy) DVTFilePath *playgroundFilePath; // @synthesize playgroundFilePath=_playgroundFilePath;
- (void).cxx_destruct;
- (void)main;
- (id)initWithPlaygroundContext:(id)arg1 swiftSourceFiles:(id)arg2 buildProductsPath:(id)arg3 sourcesModuleName:(id)arg4;

@end