//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol IDEPlaygroundAppBundleCreator <NSObject>
@property(readonly) DVTDevice *device;
@property(readonly) DVTSDK *sdk;
@property(readonly, copy) DVTFilePath *auxiliarySourceFrameworkSearchPath;
@property(readonly, copy) DVTFilePath *frameworkSearchPath;
@property(readonly, copy) DVTFilePath *resourcesPath;
@property(readonly, copy) NSString *uniquingString;
@property(readonly, copy) NSUUID *playgroundUUID;
@property(readonly, copy) NSString *playgroundName;
- (id <IDEPlaygroundAppBundle>)constructPlaygroundAppBundleInDirectoryAtPath:(DVTFilePath *)arg1 error:(id *)arg2;
- (id)initWithPlaygroundName:(NSString *)arg1 UUID:(NSUUID *)arg2 uniquingString:(NSString *)arg3 resourcesPath:(DVTFilePath *)arg4 frameworkSearchPath:(DVTFilePath *)arg5 auxiliarySourceFrameworkSearchPath:(DVTFilePath *)arg6 sdk:(DVTSDK *)arg7 device:(DVTDevice *)arg8;
@end