//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEPlaygroundLayoutManager : DVTLayoutManager
{
    DVTMutableRangeArray *_sectionCharRanges;
    CDStruct_bf6d4a14 _inlineToysInset;
}

+ (Class)_dvtDefaultTypesetterClass;
@property CDStruct_bf6d4a14 inlineToysInset; // @synthesize inlineToysInset=_inlineToysInset;
- (void).cxx_destruct;
- (void)mergeAnnotationsAtParagraphIndex:(unsigned long long)arg1;
- (void)textStorage:(id)arg1 didReplaceCharactersInRange:(struct _NSRange)arg2 withString:(id)arg3 changeInLength:(long long)arg4;
- (id)accessoryAnnotationsInTextContainer:(id)arg1;
- (void)removeSectionWithCharacterRange:(struct _NSRange)arg1;
- (void)addSectionWithCharacterRange:(struct _NSRange)arg1;
@property(copy) NSArray *sectionCharacterRanges;
- (id)initWithCoder:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly) IDEPlaygroundTextView *firstTextView; // @dynamic firstTextView;
@property(readonly) IDEPlaygroundTextView *textViewForBeginningOfSelection; // @dynamic textViewForBeginningOfSelection;

@end