//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEPlaygroundAssets : NSObject
{
}

+ (id)alternateImageForToyMultipleRepresentationIcon;
+ (id)imageForToyMultipleRepresentationIcon;
+ (id)alternateImageForToySingleRepresentationIcon;
+ (id)imageForToySingleRepresentationIcon;
+ (id)alternateImageForToySpecializedGraphRepresentationIcon;
+ (id)imageForToySpecializedGraphRepresentationIcon;
+ (id)alternateImageForToyCloseButton;
+ (id)imageForToyCloseButton;

@end