//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEPlaygroundQuickLookForStructure : NSViewController <DVTOutlineViewDelegate, NSPopoverDelegate, IDEPlaygroundQuickLookProvider>
{
    NSButtonCell *_quickLookCell;
    IDEPlaygroundQuickLookPopover *_quickLookPopover;
    NSOutlineView *_outlineView;
    IDELogEntryQuickLookNode *_rootNode;
}

@property(readonly) IDELogEntryQuickLookNode *rootNode; // @synthesize rootNode=_rootNode;
@property __weak NSOutlineView *outlineView; // @synthesize outlineView=_outlineView;
- (void).cxx_destruct;
- (void)outlineView:(id)arg1 rowPreviouslyUnderMouse:(long long)arg2 rowCurrentlyUnderMouse:(long long)arg3;
- (BOOL)outlineView:(id)arg1 shouldMouseHoverForTableColumn:(id)arg2 row:(long long)arg3;
- (id)outlineView:(id)arg1 viewForTableColumn:(id)arg2 item:(id)arg3;
- (BOOL)popoverShouldClose:(id)arg1;
- (void)popoverDidShow:(id)arg1;
- (void)_showQuickLookForNode:(id)arg1 atRow:(long long)arg2;
- (void)_toggleQuickLookForClickedRow:(id)arg1;
- (double)outlineView:(id)arg1 heightOfRowByItem:(id)arg2;
- (id)quickLookViewForResultsView;
- (id)quickLookViewForNaturalSize;
@property(readonly, copy) NSAttributedString *attributedTitle;
@property(readonly) NSView *iconView;
- (void)loadView;
- (void)dealloc;
- (id)initWithStructure:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end