//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEPlaygroundEditorStackView_ML : DVTStackView_ML
{
    IDESourceCodePlaygroundSectionViewController *_sourceCodePlaygroundSectionViewController;
    NSMapTable *_playgroundTextViewPreparedRectObservers;
}

- (void).cxx_destruct;
- (BOOL)isOpaque;
- (void)willRemoveSubview:(id)arg1;
- (void)didAddSubview:(id)arg1;
- (id)findSubviewOfClass:(Class)arg1 inViewHierarchy:(id)arg2;
- (void)recursivelyPrepareContentInRect:(struct CGRect)arg1 view:(id)arg2;
- (void)prepareContentInRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end