//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEPlaygroundAuxiliarySourceFrameworkStructure : NSObject
{
    DVTFilePath *_buildProductsPath;
    DVTFilePath *_frameworkBundlePath;
    DVTFilePath *_originalResourcesDirectory;
    DVTFilePath *_resourcesFolderPath;
    DVTFilePath *_modulesFolderPath;
    DVTFilePath *_moduleBundlePath;
    DVTFilePath *_modulePath;
    DVTFilePath *_dylibPath;
}

@property(copy) DVTFilePath *dylibPath; // @synthesize dylibPath=_dylibPath;
@property(copy) DVTFilePath *modulePath; // @synthesize modulePath=_modulePath;
@property(copy) DVTFilePath *moduleBundlePath; // @synthesize moduleBundlePath=_moduleBundlePath;
@property(copy) DVTFilePath *modulesFolderPath; // @synthesize modulesFolderPath=_modulesFolderPath;
@property(copy) DVTFilePath *resourcesFolderPath; // @synthesize resourcesFolderPath=_resourcesFolderPath;
@property(copy) DVTFilePath *originalResourcesDirectory; // @synthesize originalResourcesDirectory=_originalResourcesDirectory;
@property(copy) DVTFilePath *frameworkBundlePath; // @synthesize frameworkBundlePath=_frameworkBundlePath;
@property(copy) DVTFilePath *buildProductsPath; // @synthesize buildProductsPath=_buildProductsPath;
- (void).cxx_destruct;
- (BOOL)createDirectoryStructureIfNecessary:(id *)arg1;
- (id)initWithBuildProductsPath:(id)arg1 resourcesDirectory:(id)arg2 sourcesModuleName:(id)arg3;

@end