//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol IDEPlaygroundQuickLookProvider <NSObject>
@property(readonly, copy) NSAttributedString *attributedTitle;
@property(readonly) NSView *iconView;
- (NSView *)quickLookViewForResultsView;
- (NSView *)quickLookViewForNaturalSize;

@optional
- (NSView *)quickLookViewForUnadornedView;
- (NSView *)iconOnlyViewForCollectionView;
- (NSView *)quickLookViewForCollectionView;
@end