//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEPlaygroundExecutionIssueProvider : IDEIssueProvider
{
    DVTDelayedInvocation *_batchedUpdateInvocation;
    DVTNotificationToken *_playgroundIssuesChangedToken;
    DVTObservingToken *_openDocumentsChangedToken;
    BOOL _openDocumentsChanged;
    NSSet *_observedDocumentFilePaths;
    NSMutableSet *_changedDocumentFilePaths;
    id <DVTInvalidation> _fileReferenceObserverToken;
    NSMutableSet *_workspaceFilePaths;
    BOOL _workspaceContentChanged;
    NSMapTable *_filePathToIssueProviderContext;
}

- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (id)issueProviderContextForFilePath:(id)arg1;
- (id)displayNameForIssueTypeIdentifier:(id)arg1;
- (void)playgroundIssuesChanged:(id)arg1;
- (id)initWithIssueManager:(id)arg1 extension:(id)arg2;

@end