//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEQuicklookCollectionViewItem : NSCollectionViewItem
{
    NSView *_quicklookView;
}

@property(retain) NSView *quicklookView; // @synthesize quicklookView=_quicklookView;
- (void).cxx_destruct;
- (id)quickLookViewForSingleLineSize;
- (void)setSelected:(BOOL)arg1;
- (void)setRepresentedObject:(id)arg1;

@end