//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDESourceLanguageServiceSwiftDiagnosticItems : NSObject <IDESourceLanguageServiceSwiftDiagnosticItems>
{
    NSArray *_diagnosticItems;
    unsigned long long _diagnosticLevel;
}

@property(readonly) unsigned long long diagnosticLevel; // @synthesize diagnosticLevel=_diagnosticLevel;
@property(readonly, copy) NSArray *diagnosticItems; // @synthesize diagnosticItems=_diagnosticItems;
- (void).cxx_destruct;
- (id)initWithDiagnosticItems:(id)arg1 level:(unsigned long long)arg2;

@end