//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDESourceCodePlaygroundSectionAccessoryViewAnnotation : DVTAccessoryViewAnnotation
{
    IDESourceCodePlaygroundSectionAnnotationProvider *_annotationProvider;
    NSMutableOrderedSet *_loggerResults;
}

@property(copy) NSMutableOrderedSet *loggerResults; // @synthesize loggerResults=_loggerResults;
@property IDESourceCodePlaygroundSectionAnnotationProvider *annotationProvider; // @synthesize annotationProvider=_annotationProvider;
- (void).cxx_destruct;
- (id)currentStateInTextView:(id)arg1;
- (void)drawLineHighlightInRect:(struct CGRect)arg1 textView:(id)arg2;
- (void)setNeedsInvalidateWithoutLayout;
- (void)setNeedsInvalidate;
- (BOOL)wantsMergeAnnotations;
- (id)initWithViewControllerClass:(Class)arg1;

// Remaining properties
@property(readonly) IDESourceCodePlaygroundSectionAnnotationViewController *viewController; // @dynamic viewController;

@end