//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDESwiftInterfaceSummaryDocument : IDEEditorDocument <IDEEditorDocumentDerivedContentClient>
{
    IDEEditorDocument *_originalDocument;
    NSString *_summaryHTML;
    IDEEditorDocumentDerivedContentProvider *_derivedContentProvider;
}

@property(retain) IDEEditorDocumentDerivedContentProvider *derivedContentProvider; // @synthesize derivedContentProvider=_derivedContentProvider;
@property(copy) NSString *summaryHTML; // @synthesize summaryHTML=_summaryHTML;
@property(retain) IDEEditorDocument *originalDocument; // @synthesize originalDocument=_originalDocument;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (int)readOnlyStatus;
- (void)derivedContentProviderDidBecomeInvalid:(id)arg1;
- (void)derivedContentProviderDidUpdateContent:(id)arg1;
- (void)setFileURL:(id)arg1;
- (id)dataOfType:(id)arg1 error:(id *)arg2;
- (BOOL)readFromURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end