//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDESwiftInterfaceSummaryViewer : IDEEditor
{
    struct CGRect _visibleRectAtLastReload;
    WebView *_webView;
}

@property(retain) WebView *webView; // @synthesize webView=_webView;
- (void).cxx_destruct;
- (void)viewWillUninstall;
- (void)webView:(id)arg1 didFinishLoadForFrame:(id)arg2;
- (void)viewDidInstall;
- (void)viewDidLoad;

@end