//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEStructureTableCellView : NSTableCellView
{
    NSView *_customViewContainer;
    NSButton *_quickLookButton;
}

@property __weak NSButton *quickLookButton; // @synthesize quickLookButton=_quickLookButton;
@property __weak NSView *customViewContainer; // @synthesize customViewContainer=_customViewContainer;
- (void).cxx_destruct;
- (void)setBackgroundStyle:(long long)arg1;
- (id)_attributedString;
- (void)setObjectValue:(id)arg1;
- (void)awakeFromNib;

@end