//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol IDEToyHostingView
@property(retain, nonatomic) NSColor *selectedBorderColor;
@property(retain, nonatomic) NSColor *backgroundColor;
@property(copy) CDUnknownBlockType mouseDownHandler;
@property(copy) CDUnknownBlockType mouseTrackingHandler;
@property(nonatomic) BOOL toyIsHighlighted;
@property(nonatomic) BOOL toyIsSelected;
@end