//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol IDEToyViewControllerDelegate <NSObject>
@property(retain) NSColor *customRightBorderColor;
@property(retain) NSColor *customLeftBorderColor;

@optional
- (void)toyViewController:(IDEToyViewController *)arg1 didSelectNewResultDisplayDate:(NSDate *)arg2;
@end