//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEToyHostingView_inline : NSView <IDEToyHostingView>
{
    NSTrackingArea *_trackingArea;
    struct CGRect _pointerRect;
    struct CGRect _horizontalResizingRect;
    struct CGRect _verticalResizingRect;
    struct CGRect _diagonalResizingRect;
    unsigned long long _resizeAxis;
    BOOL _toyIsSelected;
    BOOL _toyIsHighlighted;
    CDUnknownBlockType _mouseTrackingHandler;
    CDUnknownBlockType _mouseDownHandler;
    NSColor *_backgroundColor;
    NSColor *_selectedBorderColor;
    CDUnknownBlockType _mouseDragHandler;
}

@property(copy) CDUnknownBlockType mouseDragHandler; // @synthesize mouseDragHandler=_mouseDragHandler;
@property(retain, nonatomic) NSColor *selectedBorderColor; // @synthesize selectedBorderColor=_selectedBorderColor;
@property(retain, nonatomic) NSColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(copy) CDUnknownBlockType mouseDownHandler; // @synthesize mouseDownHandler=_mouseDownHandler;
@property(copy) CDUnknownBlockType mouseTrackingHandler; // @synthesize mouseTrackingHandler=_mouseTrackingHandler;
@property(nonatomic) BOOL toyIsHighlighted; // @synthesize toyIsHighlighted=_toyIsHighlighted;
@property(nonatomic) BOOL toyIsSelected; // @synthesize toyIsSelected=_toyIsSelected;
- (void).cxx_destruct;
- (id)_cursorForResizeAxis:(unsigned long long)arg1;
- (void)updateLayerDisplay;
- (void)_updateDisplayForCurrentState;
- (void)updateTrackingAreas;
- (void)mouseDragged:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)resetCursorRects;
- (id)hitTest:(struct CGPoint)arg1;
- (void)viewDidMoveToSuperview;
- (id)initWithFrame:(struct CGRect)arg1;

@end