//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEValueHistorySingleValueTextField : NSTextField
{
    struct CGSize _forcedIntrinsicContentSize;
}

@property struct CGSize forcedIntrinsicContentSize; // @synthesize forcedIntrinsicContentSize=_forcedIntrinsicContentSize;
- (struct CGSize)intrinsicContentSize;
- (void)updateIntrinsicContentSizeForSize:(struct CGSize)arg1;

@end