//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEValueHistoryColorViewController : IDEValueHistoryToyViewController <NSCollectionViewDelegate>
{
    IDESelectionCollectionViewController *_collectionViewController;
    NSMutableArray *_mutableContents;
}

+ (id)displayableReflectionTags;
@property(retain) NSMutableArray *mutableContents; // @synthesize mutableContents=_mutableContents;
@property(retain) IDESelectionCollectionViewController *collectionViewController; // @synthesize collectionViewController=_collectionViewController;
- (void).cxx_destruct;
- (void)_setViewsStartingAtIndex:(unsigned long long)arg1 fromResults:(id)arg2;
- (void)renderResultsForceRedraw:(BOOL)arg1;
- (void)playgroundExecutionEndedAndCompleted:(BOOL)arg1;
- (struct CGSize)preferredContentSizeConstrainedToSize:(struct CGSize)arg1;
- (void)primitiveInvalidate;
- (void)viewDidLoad;
- (id)initWithToy:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end