//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEValueHistoryMultipleStringViewController : IDEValueHistoryToyViewController
{
    NSTextStorage *_textStorage;
    NSTextView *_textView;
}

+ (id)displayableReflectionTags;
@property(retain) NSTextView *textView; // @synthesize textView=_textView;
@property(retain) NSTextStorage *textStorage; // @synthesize textStorage=_textStorage;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (void)renderResultsForceRedraw:(BOOL)arg1;
- (void)playgroundExecutionEndedAndCompleted:(BOOL)arg1;
- (void)playgroundExecutionStarted;
- (id)toolTip;
- (id)alternateIconImage;
- (id)iconImage;
- (double)preferredVerticalInset;
- (struct CGSize)preferredContentSizeConstrainedToSize:(struct CGSize)arg1;
- (void)viewDidLoad;
- (id)initWithToy:(id)arg1;

@end