//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DBGProcess : IDEDebugProcess
{
    NSMutableSet *_threadsAutoRefreshStackFrames;
    DBGThread *_currentThread;
    DBGStackFrame *_currentStackFrame;
    NSMutableArray *_memoryDatas;
    DVTObservingToken *_currentStackFrameValidityObserver;
    DVTStackBacktrace *_currentStackFrameBacktraceWhenSet;
    BOOL _threadsAutoRefreshStackFramesDone;
    int _controlState;
    int _PID;
    NSString *_name;
    NSArray *_threads;
    NSArray *_queues;
}

+ (id)keyPathsForValuesAffectingName;
+ (id)keyPathsForValuesAffectingThreads;
+ (void)initialize;
@property(nonatomic) BOOL threadsAutoRefreshStackFramesDone; // @synthesize threadsAutoRefreshStackFramesDone=_threadsAutoRefreshStackFramesDone;
@property(nonatomic) int PID; // @synthesize PID=_PID;
@property(nonatomic) int controlState; // @synthesize controlState=_controlState;
- (id)queues;
@property(copy, nonatomic) NSArray *threads; // @synthesize threads=_threads;
- (void)setName:(id)arg1;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
@property(readonly, nonatomic) unsigned long long addressByteSize;
- (void)removeMemoryData:(id)arg1;
- (void)autoUpdateAllMemoryDatas;
- (id)readMemoryAtAddress:(unsigned long long)arg1 numberOfBytes:(unsigned long long)arg2 progressHandler:(CDUnknownBlockType)arg3 resultHandler:(CDUnknownBlockType)arg4;
- (id)readMemoryAtAddress:(unsigned long long)arg1 numberOfBytes:(unsigned long long)arg2 resultHandler:(CDUnknownBlockType)arg3;
- (void)rawMemoryDataForAddressExpression:(id)arg1 numberOfBytes:(unsigned long long)arg2 resultHandler:(CDUnknownBlockType)arg3;
- (id)memoryDataForUUID:(id)arg1;
- (id)memoryDataForAddressOfExpression:(id)arg1 numberOfBytes:(unsigned long long)arg2;
- (void)setCurrentStackFrame:(id)arg1;
- (id)currentStackFrame;
- (void)setCurrentThread:(id)arg1;
- (id)currentThread;
- (void)deregisterThreadAutoRefreshesStackFrames:(id)arg1;
- (void)registerThreadAutoRefreshesStackFrames:(id)arg1;
- (BOOL)_shouldSelectFirstSymbolFrame;
- (BOOL)_shouldLookForStackFrameWithDebugSymbols;
- (void)setInitialCurrentStackFrame;
- (BOOL)isPaused;
- (void)setQueues:(id)arg1;
- (id)name;
@property(readonly) NSString *displayStatus;
- (id)initWithDebugSession:(id)arg1;
- (id)contentDelegateUIExtensionIdentifier;

// Remaining properties
@property(readonly, nonatomic) NSArray *memoryDatas; // @dynamic memoryDatas;
@property(retain) NSMutableArray *mutableMemoryDatas; // @dynamic mutableMemoryDatas;

@end