//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DBGStackFrame : IDEStackFrame
{
    DVTObservingToken *_debugSessionStateObserver;
    BOOL _returnValueIsValid;
    BOOL _settingDisassembly;
    DBGDataValue *_returnValue;
    NSString *_instructionPointerAddressString;
    NSArray *_locals;
    NSArray *_arguments;
    NSArray *_fileStatics;
    NSArray *_registers;
    DBGDisassemblyInstructionList *_disassembly;
}

+ (id)stackFrameForDisassemblyURL:(id)arg1;
+ (id)disassemblyURLForStackFrame:(id)arg1 inDebugSession:(id)arg2;
@property(nonatomic) BOOL settingDisassembly; // @synthesize settingDisassembly=_settingDisassembly;
@property(retain, nonatomic) DBGDisassemblyInstructionList *disassembly; // @synthesize disassembly=_disassembly;
@property(nonatomic) BOOL returnValueIsValid; // @synthesize returnValueIsValid=_returnValueIsValid;
@property(readonly, nonatomic) NSArray *registers; // @synthesize registers=_registers;
@property(readonly, nonatomic) NSArray *fileStatics; // @synthesize fileStatics=_fileStatics;
@property(readonly, nonatomic) NSArray *arguments; // @synthesize arguments=_arguments;
@property(readonly, nonatomic) NSArray *locals; // @synthesize locals=_locals;
@property(copy, nonatomic) NSString *instructionPointerAddressString; // @synthesize instructionPointerAddressString=_instructionPointerAddressString;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (void)evaluateExpression:(id)arg1 options:(id)arg2 withResultBlock:(CDUnknownBlockType)arg3;
- (void)evaluateExpression:(id)arg1 withResultBlock:(CDUnknownBlockType)arg2;
- (void)requestDataValueForSymbol:(id)arg1 symbolKind:(id)arg2 atLocation:(id)arg3 onQueue:(id)arg4 withResultBlock:(CDUnknownBlockType)arg5;
- (id)dataValuesToInvalidate;
- (void)primitiveSetReturnValueIsValid:(BOOL)arg1;
- (void)primitiveSetReturnValue:(id)arg1;
@property(retain, nonatomic) DBGDataValue *returnValue; // @synthesize returnValue=_returnValue;
- (void)primitiveSetInstructionPointerAddressString:(id)arg1;
- (id)initWithParentThread:(id)arg1 frameNumber:(id)arg2 framePointer:(id)arg3 name:(id)arg4;
- (BOOL)hasSameDisassemblyURL:(id)arg1;

@end