//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDESourceLanguageEditorExtension : NSObject <IDESourceLanguageEditorExtension, DVTInvalidation>
{
    IDESourceCodeEditor *_editor;
}

+ (void)initialize;
+ (Class)editorExtensionClassForLanguage:(id)arg1;
+ (id)editorExtensionForLanguage:(id)arg1 withEditor:(id)arg2;
@property(readonly) __weak IDESourceCodeEditor *editor; // @synthesize editor=_editor;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (id)initWithEditor:(id)arg1;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end