//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTTableRowView : NSTableRowView
{
    DVTTableCellViewVibrantView *_secondaryHighlightView;
    BOOL _drawsSecondaryHighlight;
    NSColor *_rowGridLineColor;
    CDStruct_2b6e6e30 _rowGridLineInset;
}

@property(retain) NSColor *rowGridLineColor; // @synthesize rowGridLineColor=_rowGridLineColor;
@property CDStruct_2b6e6e30 rowGridLineInset; // @synthesize rowGridLineInset=_rowGridLineInset;
@property(nonatomic) BOOL drawsSecondaryHighlight; // @synthesize drawsSecondaryHighlight=_drawsSecondaryHighlight;
- (void).cxx_destruct;
- (BOOL)isOpaque;
- (void)didAddSubview:(id)arg1;
- (void)_updateSecondaryHighlightViewFrame;
- (void)setSelected:(BOOL)arg1;
- (void)drawBackgroundInRect:(struct CGRect)arg1;
- (long long)groupRowStyle2;
- (void)drawSeparatorInRect:(struct CGRect)arg1;
- (struct CGRect)separatorRectForTable:(id)arg1;
- (CDStruct_2b6e6e30)rowGridLineInsetForTableView:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dvt_commonInit;

@end