//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTServicesTypeLoadingContext : NSObject
{
    NSMutableDictionary *_typeNameToType;
    NSMutableDictionary *_typeNameToPropertyLoadingBlock;
    NSMutableSet *_extensionsLoaded;
}

- (void).cxx_destruct;
- (id)typeWithName:(id)arg1;
- (void)addPropertyLoadBlockForType:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)_loadTypeExtension:(id)arg1;
- (void)loadAllTypes;
@property(readonly, nonatomic) NSSet *types;
- (id)init;

@end