//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTServicesRequest : NSObject
{
    DVTServicesSession *_session;
}

@property(readonly, nonatomic) DVTServicesSession *session; // @synthesize session=_session;
- (void).cxx_destruct;
- (id)_userAgentForExecutionContext:(long long)arg1;
- (id)userAgent;
@property(readonly) NSDictionary *standardXcodeHeaders;
@property(readonly) NSURL *requestURL;
- (id)initWithSession:(id)arg1;
- (id)init;

@end