//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTTimer : NSObject <DVTCancellable>
{
    NSObject<OS_dispatch_queue> *_queue;
    NSObject<OS_dispatch_source> *_timer;
    NSObject<OS_dispatch_group> *_group;
    CDUnknownBlockType _callback;
}

+ (id)timerWithInterval:(double)arg1 andCallback:(CDUnknownBlockType)arg2;
+ (id)timerWithInterval:(double)arg1 leeway:(double)arg2 andCallback:(CDUnknownBlockType)arg3;
- (void).cxx_destruct;
- (void)runSynchronously;
- (void)start;
@property(readonly, getter=isCancelled) BOOL cancelled;
- (void)cancel;
- (id)initWithInterval:(double)arg1 leeway:(double)arg2 andCallback:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end