//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IBImagePickerInspectorProperty : IDEInspectorProperty <IBImagePickerInspectorPopoverContentViewDelegate>
{
    IBImagePickerInspectorPopoverContentView *_popoverContentView;
    IDEInspectorKeyPath *_valueKeyPath;
    IDEInspectorKeyPath *_imagesKeyPath;
    IDEInspectorKeyPath *_toolTipsKeyPath;
    NSPopover *_popover;
    NSButton *_popoverButton;
}

- (void).cxx_destruct;
- (void)popoverContentView:(id)arg1 clickedImageAtIndex:(long long)arg2;
- (double)baseline;
- (void)setupRefreshTriggersAndConfigure;
- (void)refresh;
- (void)loadView;
- (void)buttonClicked:(id)arg1;
- (id)valueKeyPath;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end