//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IBPlatform : NSObject <IBScopedSingleton>
{
    NSSet *_objectLibraryAssetProviderExtensions;
    NSSet *_documentDependencies;
    NSSet *_classDescriptionsExtensions;
    NSSet *_buildEnvironmentVerifiers;
    NSSet *_connectionExtensions;
    NSSet *_excludedFrameworksExtensions;
    NSSet *_sourceCodeParserExtensions;
    NSSet *_connectionClasses;
    NSSet *_segueClasses;
    NSArray *_displayOrderedConfigurations;
}

+ (id)platformForBuildSettingPlatformIdentifier:(id)arg1;
+ (id)instanceWithIdentifier:(id)arg1;
+ (id)allInstances;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (Class)documentDesignablesDispatcherClass;
- (BOOL)supportsLaunchScreen;
- (Class)previewGeniusResultsItemGroupClass;
- (id)validateVersion:(id)arg1 forCompilingDocument:(id)arg2;
- (id)xibPackageContentFileNames;
- (id)storyboardPackageContentFileNames;
- (id)sourceCodeParserClasses;
- (id)frameworksExcludedFromSourceScanning;
- (Class)fallbackSegueClassForUnknownSegueKind;
- (id)segueClasses;
- (id)connectionClasses;
- (id)connectionExtensionForConnectionClass:(Class)arg1;
- (id)documentDependencyForType:(id)arg1;
- (id)documentDependencies;
- (id)objectLibraryAssetProviderExtensions;
- (id)excludedFrameworkExtensions;
- (id)buildEnvironmentVerifiers;
- (id)sourceCodeParserExtensions;
- (id)connectionExtensions;
- (id)classDescriptionsExtensions;
- (id)extensionsForExtensionPoint:(id)arg1;
- (BOOL)matchesExtension:(id)arg1;
- (id)typeIdentifierForPreservingContentsWhenWritingDocument;
- (id)xibHybridPackageType;
- (id)xibHybridPackageEditableDocumentFilename;
- (id)xibPreferredFileType;
- (Class)userDefinedRuntimeAttributesPlaceholderClass;
- (void)updateDefaultSimulatedMetricsAfterChangingTargetRuntimeForDocument:(id)arg1;
- (id)segueTemplateToControllerKeyPath;
- (Class)simulatedMetricsContainerClass;
- (id)defaultStoryboardSegueClassName;
- (void)populateAdditionalSearchableAttributeKeyPaths:(id)arg1 ofClass:(Class)arg2 forInspectorCategory:(id)arg3;
- (void)populateAdditionalInspectors:(id)arg1 ofClass:(Class)arg2 forCategory:(id)arg3;
- (id)containerObserverForInterfaceBuilderDocumentsIdentifier;
- (void)fontsObserverInvalidated;
- (void)notifyObjectsFontsDidChange:(id)arg1;
- (void)unregisterCustomFontsWithURLs:(id)arg1;
- (void)registerCustomFontsWithURLs:(id)arg1;
- (Class)resourceManagerClass;
- (void)prepareToDecodeDocumentContentWithKeyedUnarchiver:(id)arg1;
- (Class)designedClassForEncodedClassName:(id)arg1;
- (void)unarchivePlatformDependentDocumentManagedDataForObject:(id)arg1 withDocumentUnarchiver:(id)arg2;
- (void)archivePlatformDependentDocumentManagedDataForObject:(id)arg1 withDocumentArchiver:(id)arg2;
- (id)sanitizedVersion:(id)arg1 forDocumentDependency:(id)arg2;
- (void)documentDidUpgradeDevelopmentTarget:(id)arg1;
- (BOOL)supportPerConfigurationProperties;
- (id)archiveKeyForUsesConfigurations;
- (id)autolayoutStatusRequesterForTargetRuntime:(id)arg1 liveViewsManager:(id)arg2;
- (Class)autolayoutFrameDecisionDriverClass;
- (Class)autolayoutEngineClass;
- (Class)arbitrationUnitClass;
- (BOOL)hasRemoteSimulator;
- (id)autolayoutDescriptiveTextForPriority:(float)arg1;
- (id)messageForUpgradingFromXcode4;
- (long long)autolayoutMinSystemVersion;
- (id)classNamesThatDoNotSupportZeroingWeakReferences;
- (id)bonusedClassNamesForGeniusOrdering;
- (id)penalizedClassNamesForGeniusOrdering;
- (id)ignoredConnectionLabelsForGeniusOrdering;
- (BOOL)connectToSourceCodeShouldReleaseInstanceVariables;
- (BOOL)connectToSourceCodeShouldInsertNonAtomicProperties;
- (long long)defaultStorageTypeForMRROutlets;
- (id)firstOSVersionWithWeakReferences;
- (Class)actionConnectionClass;
- (id)xibFirstResponderMemberID;
- (id)xibFilesOwnerMemberID;
- (BOOL)documentEditor:(id)arg1 validateUserInterfaceItem:(id)arg2;
- (void)document:(id)arg1 didChangeTargetRuntimeWithContext:(id)arg2;
- (void)document:(id)arg1 willChangeTargetRuntimeWithContext:(id)arg2;
- (void)finishChangingTargetRuntimeForDocument:(id)arg1;
- (long long)allSystemsTarget;
- (id)defaultTargetRuntimeForArchiving;
- (id)defaultTargetRuntime;
- (Class)idiomClass;
- (Class)targetRuntimeClass;
- (id)targetRuntimes;
- (id)targetRuntimeWithArchiveIdentifier:(id)arg1 variantIdentifier:(id)arg2;
- (id)targetRuntimeWithIdentifier:(id)arg1;
- (BOOL)downgradingToAutoIncrementingIDsIsEnabled;
- (BOOL)shouldOpenDocument:(id)arg1 error:(id *)arg2;
- (id)systemDocumentDependency;
- (id)interfaceBuilderDocumentDependency;
- (id)deploymentVersionBuildSetting;
- (id)runtimeConfigurableConstraintConstantKeyPath;
- (void)registerMemberConfigurationVariables;
- (id)buildSettingIdentifier;
- (id)backingPlatform;
- (id)pluginName;
- (id)baseInterfaceBuilderDocumentType;
- (Class)documentPlatformAdapterClass;
- (id)operatingSystemName;
- (id)identifier;
- (void)didRegisterSharedInstance;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end