//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol IBPrimarySceneObject <NSObject>
@property(copy, nonatomic) IBSimulatedMetricsContainer *inheritedSimulatedMetrics;
- (NSString *)ibShortDisplayName;
- (BOOL)ibIsPrimarySceneObject:(NSObject<IBPrimarySceneObject> *)arg1 validSplitViewDetailWithSegue:(IBStoryboardRelationshipSegue *)arg2;
- (BOOL)ibIsPrimarySceneObject:(NSObject<IBPrimarySceneObject> *)arg1 validSplitViewMasterWithSegue:(IBStoryboardRelationshipSegue *)arg2;
- (BOOL)ibIsValidPushReceiver;
- (BOOL)ibSegueTemplatesAreTopLevel;
- (void)ibResizeToEffectiveSimulatedSizeForSceneTreeDragImageNode;
- (void)ibDidBecomeControllerForCompilationGroup;
- (void)ibAddStoryboardSegueTemplate:(IBAbstractStoryboardSegueTemplate *)arg1;
- (void)ibWillResignSourceControllerForSegue:(IBAbstractSegueConnection *)arg1;
- (void)ibDidBecomeSourceControllerForSegue:(IBAbstractSegueConnection *)arg1;
- (IBSimulatedMetricsContainer *)ibInheritableMetricsForDownstreamController:(id <IBPrimarySceneObject>)arg1 viaSegue:(IBAbstractSegueConnection *)arg2;
- (void)ibEffectiveSimulatedMetricsDidChange;
- (NSSet *)ibOutgoingSeguesInDocument:(IBStoryboardDocument *)arg1;
- (NSSet *)ibIncomingSeguesIncludingSelfOriginated:(BOOL)arg1;
- (NSString *)ibEffectiveStoryboardIdentifier;
- (NSImage *)ibImageForOwnedScene;

@optional
@property(nonatomic) BOOL ibInspectedIsDesignatedEntryPoint;
- (NSString *)uniqueIdentifierForStoryboardCompilation;
- (void)ibPrepareTopLevelControllerForStoryboardCompilation;
@end