//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IBPreviewResultView : NSView
{
    NSView *_contentView;
    NSImageView *_imageView;
    NSTrackingArea *_trackingArea;
    BOOL _mouseInside;
    NSArray *_visibleActionButtonConstraints;
    NSLayoutConstraint *_actionButtonToTitleFieldHorizontalSpacingConstraint;
    NSLayoutConstraint *_scrollViewWidthConstraint;
    NSLayoutConstraint *_scrollViewHeightConstraint;
    BOOL _selected;
    BOOL _showsFirstResponder;
    IBImageButton *_actionButton;
    NSTextField *_titleField;
    id _representedObject;
    id <IBPreviewResultViewDelegate> _delegate;
    double _defaultActionButtonToTitleFieldHorizontalSpacing;
}

+ (id)titleTextField;
@property(readonly) double defaultActionButtonToTitleFieldHorizontalSpacing; // @synthesize defaultActionButtonToTitleFieldHorizontalSpacing=_defaultActionButtonToTitleFieldHorizontalSpacing;
@property __weak id <IBPreviewResultViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) BOOL showsFirstResponder; // @synthesize showsFirstResponder=_showsFirstResponder;
@property(nonatomic, getter=isSelected) BOOL selected; // @synthesize selected=_selected;
@property(retain) id representedObject; // @synthesize representedObject=_representedObject;
@property(retain) NSTextField *titleField; // @synthesize titleField=_titleField;
@property(retain) IBImageButton *actionButton; // @synthesize actionButton=_actionButton;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (id)effectiveBorderColor;
- (void)updateTrackingAreas;
- (void)installTrackingArea;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (id)hitTest:(struct CGPoint)arg1;
- (void)mouseDown:(id)arg1;
- (void)setMouseInside:(BOOL)arg1;
@property double spacingBetweenActionButtonAndTitleField;
@property(retain) NSImage *contentImage;
- (void)disableContentScrolling;
- (void)enableContentScrollingWithClippingSize:(struct CGSize)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end