//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol IBStoryboardCanvasLink <NSObject>
@property(readonly) BOOL canvasLinkWantsExclusiveHook;
@property(readonly) BOOL canvasLinkRequiresSourceCanvasFrame;
@property(readonly) NSObject<IBPrimarySceneObject> *canvasLinkDestination;
@property(readonly) NSObject<IBPrimarySceneObject> *canvasLinkSource;
- (BOOL)isSelectable;
@end