//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IBStoryboardInitialViewControllerCanvasLink : NSObject <IBStoryboardCanvasLink>
{
    BOOL _selected;
    NSObject<IBStoryboardEntryPointIndicator> *_entryPointIndicator;
    NSObject<IBPrimarySceneObject> *_canvasLinkSource;
    NSObject<IBPrimarySceneObject> *_canvasLinkDestination;
}

@property(nonatomic, getter=isSelected) BOOL selected; // @synthesize selected=_selected;
@property(readonly) NSObject<IBPrimarySceneObject> *canvasLinkDestination; // @synthesize canvasLinkDestination=_canvasLinkDestination;
@property(retain) NSObject<IBPrimarySceneObject> *canvasLinkSource; // @synthesize canvasLinkSource=_canvasLinkSource;
@property(retain) NSObject<IBStoryboardEntryPointIndicator> *entryPointIndicator; // @synthesize entryPointIndicator=_entryPointIndicator;
- (void).cxx_destruct;
- (BOOL)isSelectable;
@property(readonly) BOOL canvasLinkWantsExclusiveHook;
@property(readonly) BOOL canvasLinkRequiresSourceCanvasFrame;
- (id)initWithCanvasLinkDestination:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end