//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol IBStoryboardEntryPointIndicator <NSObject>
- (void)ibTransferToObject:(NSObject<IBPrimarySceneObject> *)arg1 fromObject:(NSObject<IBPrimarySceneObject> *)arg2 inDocument:(IBStoryboardDocument *)arg3;
- (NSString *)ibStoryboardEntryPointIndicatorCanvasTitle;
@end