//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDECodesignIssueResolutionGenerateDevelopmentProfileOption : IDECodesignIssueResolutionAbstractGenerateProfileOption
{
    NSSet *_requiredCodesignableDevices;
    DVTAppIDFeatures *_requiredFeatures;
}

@property(retain) DVTAppIDFeatures *requiredFeatures; // @synthesize requiredFeatures=_requiredFeatures;
@property(retain) NSSet *requiredCodesignableDevices; // @synthesize requiredCodesignableDevices=_requiredCodesignableDevices;
- (void).cxx_destruct;
- (id)invokeOptionWithWindowOrNil:(id)arg1;
- (id)initWithPortalSource:(id)arg1 account:(id)arg2 signingCertificate:(id)arg3 platformIdentifier:(id)arg4 bundleIdentifiers:(id)arg5 requiredCodesignableDevices:(id)arg6 requiedFeatures:(id)arg7 logAspect:(id)arg8;

@end