//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDENavigatorCrashPointCell : IDENavigatorProcessCell
{
    id <IDENavigatorCrashPointCellDelegate> _delegate;
    IDECrashPoint *_crashPoint;
    NSButtonCell *_backwardCell;
    NSButtonCell *_forwardCell;
    NSAttributedString *_sequenceText;
}

@property(retain, nonatomic) NSAttributedString *sequenceText; // @synthesize sequenceText=_sequenceText;
- (void).cxx_destruct;
- (void)setHighlighted:(BOOL)arg1;
- (void)_drawCrashLogSequenceTextWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (double)_startXForSequenceText:(struct CGRect)arg1;
- (id)_attributedStringWithString:(id)arg1 font:(id)arg2 foregroundColor:(id)arg3;
- (id)titleDropShadow;
- (void)_drawforwardButtonWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (struct CGRect)_forwardButtonRectInFrame:(struct CGRect)arg1;
- (void)_forwardButtonPressed:(id)arg1;
- (void)_drawBackwardButtonWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (id)_buttonCellWithSelector:(SEL)arg1 imageName:(id)arg2;
- (struct CGRect)_backwardButtonRectInFrame:(struct CGRect)arg1;
- (void)_backwardButtonPressed:(id)arg1;
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (struct CGRect)_rectForCrashLogSelectionForCellFrame:(struct CGRect)arg1;
- (BOOL)trackMouse:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3 untilMouseUp:(BOOL)arg4;
- (unsigned long long)hitTestForEvent:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3;
- (BOOL)_mouseLocationForEvent:(id)arg1 overForwardButtonInCellFrame:(struct CGRect)arg2 view:(id)arg3;
- (BOOL)_mouseLocationForEvent:(id)arg1 overBackwardButtonInCellFrame:(struct CGRect)arg2 view:(id)arg3;
- (BOOL)_mouseLocationForEvent:(id)arg1 overButtonRect:(struct CGRect)arg2 view:(id)arg3;
- (id)representedObjectFollowingProxyLink;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithDelegate:(id)arg1 crashPoint:(id)arg2;

@end