//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDESwiftMigrationTarget : IDEMigrationTarget
{
    IDESwiftMigrationAssistantContext *_assistantContext;
    NSString *_title;
    NSString *_subTitle;
    BOOL _fileOveridesARCSetting;
    BOOL _enabled;
}

@property BOOL enabled; // @synthesize enabled=_enabled;
@property(readonly, copy) NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(readonly, copy) NSString *title; // @synthesize title=_title;
@property(readonly) IDESwiftMigrationAssistantContext *assistantContext; // @synthesize assistantContext=_assistantContext;
- (void).cxx_destruct;
- (void)updateBuildSettings;
- (id)initWithBlueprint:(id)arg1 assistantContext:(id)arg2;

@end