//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IBTableColumnSizeInspector : IBBoundInspector
{
    NSTextField *minWidthTextField;
    NSTextField *maxWidthTextField;
    NSTextField *widthTextField;
    NSStepper *minWidthStepper;
    NSStepper *maxWidthStepper;
    NSStepper *widthStepper;
}

- (void)ok:(id)arg1;
- (void)awakeFromNib;

@end