//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IBTableColumnInspector : IBBoundInspector
{
    NSSegmentedControl *alignmentSegmentedControl;
    NSButton *editable;
    NSButton *userResizable;
    NSButton *liveResizable;
    NSTextField *identifier;
    NSTextField *title;
    NSTextField *sortKeyField;
    NSTextField *sortSelectorField;
    NSPopUpButton *sortOrderPopUp;
    NSButton *hiddenCheckBox;
}

- (void)awakeFromNib;

@end