//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface PBXStandaloneTarget : PBXProject
{
    XCProductTypeSpecification *_productType;
    NSMutableDictionary *_buildProperties;
    NSMutableArray *_buildRules;
}

+ (id)archivableRelationships;
+ (id)archivableAttributes;
- (void)awakeFromPListUnarchiver:(id)arg1;
- (void)_setProductType:(id)arg1;
- (id)_productType;
- (void)dealloc;
- (id)init;

@end